### ISSUE TITLE
[1.21 backport] Windows service Subcommand

### ISSUE THREAD

**Issue by luthermonson** [rancher/rke2#1280]
Create a service subcommand for windows to add/delete rke2 as a windows service using the service manager calls. This subcommand will be windows only and will not appear or work in linux.

e.g. 

```
rke2 agent service --add
rke2 agent service --delete
```

**Comment by rancher-max** [comment]
I have previously validated using v1.21.3-rc4+rke2r2 that the windows service add and delete are both successful. Users should follow the steps in the docs as they are correct in order to bring this up.

One thing to note, is that after adding the service, you generally will have to start the service:
```
rke2.exe agent service --add
Get-Service rke2
Start-Service rke2
```
