### ISSUE TITLE
[release-1.20] INSTALL_RKE2_COMMIT installation method does not work

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1312]
Backport fix for "INSTALL_RKE2_COMMIT installation method does not work" to branch release-1.20:
* #1252

**Comment by rancher-max** [comment]
This is encountering an error using the latest commitid from release-1.20 branch:
```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=ce36dfe0ce2e074dc5be243327b366623f76f21f sh -
[INFO]  using commit ce36dfe0ce2e074dc5be243327b366623f76f21f as release
[INFO]  downloading airgap checksums at https://storage.googleapis.com/rke2-ci-builds/rke2-images.linux-amd64-ce36dfe0ce2e074dc5be243327b366623f76f21f.tar.gz.sha256sum
curl: (22) The requested URL returned error: 404 
```

I'm okay with closing this as WONTFIX as well since generally things in 1.20 are also in 1.21 and can be validated there and do a quick check on 1.20 with an rc. Also there are less things going into 1.20 in general. If we do want to backport this fix to release-1.20 branch, I'm okay with that as well, but will leave it to the team to decide. 
@brandond @fapatel1 @cwayne18 @davidnuzik

**Comment by brandond** [comment]
@luthermonson you up for backporting this fix? Ran into this again yesterday while trying to test a PR.

**Comment by rancher-max** [comment]
Validated can install using commit on `release-1.20` branch using commitid `e89a4f5d7ddf2bbfcfea4ee8b0c978ce0c366378`
