### ISSUE TITLE
No kube-proxy for worker nodes after installation of latest rke2 v1.21.3+rke2r1

### ISSUE THREAD

**Issue by eugenegoncharuk** [rancher/rke2#1565]
RKE2 Version: 
v1.21.3+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux testnetv3-master-node1 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers and 6 worker nodes

**Describe the bug:**
After upgrade of master nodes to version v1.21.3+rke2r1, "kube-proxy" disappeared from "kube-system" namespace for worker nodes.

**Steps To Reproduce:**
- Upgraded RKE2 to the latest version 	v1.21.3+rke2r1 on all master nodes

**Expected behavior:**
there should be in total 9 kube-proxy pods running

**Actual behavior:**
kube-proxy disappeared from worker nodes, but existed for master nodes

**Additional context / logs:**
config.yaml used for master nodes
```bash
tls-san:
  - <some domain...>

node-ip: <some IP...>
kube-apiserver-arg: "kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
disable: rke2-ingress-nginx
```

**Comment by brandond** [comment]
Have you by any chance not upgraded the agents yet? As per the release notes, the rke2-kube-proxy HelmChart has been deprecated in favor of kube-proxy static pods, and will be uninstalled if not customized.

If you've only upgraded the servers, but not the agents, they won't have any kube-proxy to run since previous agent versions don't include the static pod.

**Comment by eugenegoncharuk** [comment]
I have one worker node upgraded to the latest version v1.21.3+rke2r1, but I cannot see it has up and running static kube-proxy pod for it.

**Comment by brandond** [comment]
Can you post rke2-agent logs from the agent that you have upgraded?

**Comment by eugenegoncharuk** [comment]
I have reinstalled the latest version on all the worker nodes and now I see kube-proxy static pods for them. Thank you!

**Comment by nic-hima** [comment]
@brandond I faced a similar situation & used steps exactly like @eugenegoncharuk (upgrading masters first). In the worker nodes, the old kube-proxy pods were deleted. These are the logs we got from `kubelet.log` in a worker after the upgrade:

```
0825 02:46:51.888591 2694629 kubelet.go:1661] Failed creating a mirror pod for "kube-proxy-rke2-w001<domain-name>_kube-system(<containerID>)": pods "kube-proxy-rke2-w001.<domain-name>" is forbidden: Get "https://[::1]:6443/api/v1/namespaces/kube-system/limitranges": dial tcp [::1]:6443: connect: cannot assign requested address
```

HOWEVER, the static kube-proxy pods are running:
```
$ ps -ef | grep proxy
root     2692512 2692463  0 02:41 ?        00:00:01 kube-proxy --cluster-cidr=<CIDR> --conntrack-max-per-core=0 --conntrack-tcp-timeout-close-wait=0s --conntrack-tcp-timeout-established=0s --feature-gates=IPv6DualStack=false --healthz-bind-address=127.0.0.1 --hostname-override=rke2-w001.<domain-name> --kubeconfig=/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig --proxy-mode=iptables
```

**Comment by nic-hima** [comment]
Found out that in my case it was that the kube-api-server needed to be restarted per: https://github.com/kubernetes/kubernetes/issues/95706#issue-724762736 because we had disabled IPv6 at the kernel level & the kube-apiserver was still trying to use the [::1]:6443 addr.

Went back to using 127.0.0.1:6443 after restarting all kube-apiserver processes across the master nodes. Once this was done, all of the worker `kube-proxy static-pods` magically appeared.
