### ISSUE TITLE
[Release 1.20] - s3 snapshots do not show in the rancher 2.6 UI

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#1579]
Backport of #1551

**Comment by davidnuzik** [comment]
Only 1.21 is supported in 2.6 UI so I will test with just standalone RKE2 here.
Testing from CommitId is broken according to [this issue](https://github.com/rancher/rke2/issues/1312). I will need a 1.20 RC or build to test.

**Comment by brandond** [comment]
@briandowns is there a PR for this? I don't see one linked.

**Comment by briandowns** [comment]
I backported as far as 1.21. I'll get a PR for 1.20 now.

**Comment by briandowns** [comment]
PR - https://github.com/rancher/rke2/pull/1603

**Comment by davidnuzik** [comment]
I will test just standalone RKE2 here in this issue. This is because Rancher v2.6.0 will only support rke2 1.21 and newer.

**My checks PASSED**
 
**Reproduction Steps:**

Not required as I fully understand the issue.
 
**Validation Steps:**

Host OS: Ubuntu 20.04 amd64
RKE2 version: v1.20.9+rke2r2 
Tested with a 1-node rke2 cluster.
 
Validation steps:

1. Create /etc/rancher/rke2/config.yaml with the following content. Take note we specify an s3 folder (which is what we are focusing our testing on here as per the [code change](https://github.com/rancher/rke2/pull/1603)).
```
"write-kubeconfig-mode": "0644"
"etcd-s3": true
"etcd-s3-access-key": "REDACTED_ACCESS_KEY"
"etcd-s3-bucket": "dave-secret-bucket"
"etcd-s3-endpoint": "s3.us-east-2.amazonaws.com"
"etcd-s3-folder": "dave-rke2v120"
"etcd-s3-region": "us-east-2"
"etcd-s3-secret-key": "REDACTED_SECRET_KEY"
"etcd-s3-skip-ssl-verify": true
"etcd-snapshot-retention": 2
"etcd-snapshot-schedule-cron": "50 * * * *"
```
2. Install RKE2 via the install.sh script:
`curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.20.9+rke2r2 sh -`
3. Ensure the config.yaml took properly by checking the `rke2.io/node-args` annotation on the node with kubectl.
4. A snapshot is automatically taken as per my cron schedule.
5. An on-demand snapshot is successful:
`rke2 etcd-snapshot --s3 --s3-skip-ssl-verify --s3-region "us-east-2" --s3-bucket "dave-secret-bucket" --s3-folder "dave-rke2v120" --s3-access-key "REDACTED_ACCESS_KEY" --s3-secret-key "REDACTED_SECRET_KEY"`

Result:
My scheduled snapshots and my on-demand snapshot are successfully uploaded to the bucket in the correct folder
![image](https://user-images.githubusercontent.com/45179589/129931511-f165f43c-4528-402d-a167-d81bb9cad596.png)
