### ISSUE TITLE
[release-1.21] Packaged components should not schedule on to Windows nodes

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1665]
Backport fix for **Packaged components should not schedule on to Windows nodes** to branch **release-1.21**:
* https://github.com/rancher/rke2/issues/1664

**Comment by rancher-max** [comment]
Only missing one is the new coredns-autoscaler pod:
```
$ kubectl describe -n kube-system pod/rke2-coredns-rke2-coredns-autoscaler-cb6d5df56-4vvvd
...
Node-Selectors:              <none>
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/etcd:NoExecute op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
...
```

**Comment by rancher-max** [comment]
Confirmed the two aforementioned components now have the node-selector applied using release-1.21 branch commit id `fd5706be40ddb199dbb5e8229f4c01e45038da5c`. All packaged components that were blocking windows now use this `kubernetes.io/os=linux` node selector so that they are not schedulable on Windows nodes.

The only ones that don't, which I initially forgot about in my first round of testing, are two cilium pods: `cilium` and `cilium-node-init` from their respective daemonsets. 

We only use calico on windows nodes, so this should not block anymore and should not be needed to be updated at this time, so I am closing this.
