### ISSUE TITLE
Terraform Provider for RKE2 (terraform-provider-rke2)

### ISSUE THREAD

**Issue by ondrejsika** [rancher/rke2#1676]
I'm using RKE with **terraform-provider-rke** and I love it. It would be great to have a Terraform provider for RKE2.

**Comment by stefandanaita** [comment]
Same, it would be great to have an rke2 terraform provider :(

**Comment by janlauber** [comment]
Same for me, please add this request to your roadmap.

**Comment by l-with** [comment]
I think, it is essential to have a terraform provider for rke2. Please implement.

**Comment by erSitzt** [comment]
Any news on this ? Is there anything planned or in the works ?

**Comment by erSitzt** [comment]
still want to know :)

**Comment by Martin-Weiss** [comment]
We have the terraform provider for Rancher that supports provisioning RKE2 downstream clusters. 
https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2
Wouldn’t that do the job?

**Comment by erSitzt** [comment]
@Martin-Weiss yes that would do the job... but we handle additional resources like additional/later changes to the machines, loadbalancers and dns entries via terraform/ansible and last time i checked it didnt look like it was possible to get the ips of the the nodes from the different pools/machines created ? (maybe in a hacky way but not directly ? )

The other thing i didnt like about using the the cluster resource is the assignment of ip addresses. I dont want to use dhcp because of reasons, but instead assign ranges which is easy in terraform... not so much via the rancher provider.

This is all on-prem and i have a good working setup... the only part that is a little hacky is the rke2 install part.
And as there were multiple statements that an rke2 provider is in the works i just wanted to know if there is indeed something coming...

Correct me if i'm wrong somewhere... i dont need the rke2 provider, but there never was a definitive answer if its coming or not...

**Comment by erSitzt** [comment]
That's sounds a little hacky as well 😊
I'm okay with my current deployment.. it's a modified version of DavidVTUKs examples.

But still, it would be nice to know if there won't be a rke2 provider...

**Comment by rahendatri** [comment]
Hello,

+1 for this issue.
My team need to manage several Rancher/RKE2 instances.

Suggested hack here (https://github.com/rancher/rke2/issues/1676#issuecomment-1309855633) will not fit our use case because it requires having an already popped Rancher instance.

Instead, we need to create RKE2 resources and then Rancher resources. Having an RKE2 provider will allow stateful management of Rancher on RKE2.

**Comment by snivou** [comment]
There are plans to launch, ansible is not the best way to deploy, because it is stateless.

Therefore it prevents me from upgrading to RKE2.

**Comment by caroline-suse-rancher** [comment]
For those still interested, work is being planned for a standalone RKE2 terraform module and will be tracked in #4322 :) I'll be closing this issue in favor of that one.
