### ISSUE TITLE
[release-1.21] rke2-cloud-provider port conflict with vsphere cloud provider

### ISSUE THREAD

**Issue by braunsonm** [rancher/rke2#1844]
**Environmental Info:**
RKE2 Version: v1.21.4+rke2r3

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Any

**Describe the bug:**
When using the `rancher-vsphere` cloud provider, the pod `rancher-vsphere-cpi-cloud-controller-manager` will come up and try to use port `10258`. This will fail because the process `rke2-cloud-provider` is already using this port. 

I tried killing the process but it just comes back immediately. It seems this is hard coded?

**Steps To Reproduce:**
- Install RKE2 with the following configuration
```yaml
cloud-provider-name: rancher-vsphere
```
- Configure the vSphere provider with your credentials as usual in `/var/lib/rancher/rke2/server/manifests`
- Start RKE2
- Notice that the `rancher-vsphere-cpi-cloud-controller-manager` never comes up

**Expected behavior:**
The ports should not clash and vSphere CPI should work

**Actual behavior:**
The ports clash and vSphere CPI never starts

**Logs:**
```
... <spam output of all the command flags being used> ..
Generated self-signed cert in-memory
failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use
```

```
$ fuser 10258/tcp
10258/tcp: 1798
$ ls -l /proc/1798
...
lrwxrwxrwx 1 root root 0 Sep 17 20:08 exe -> /usr/local/bin/rke2-cloud-provider
```

**Comment by brandond** [comment]
adding `disable-cloud-controller: true` to your config should work around this, but you're correct that we should be doing that automatically.

**Comment by braunsonm** [comment]
Thanks @brandond I can confirm that works

**Comment by brandond** [comment]
@braunsonm did you by any chance initially start RKE2 with the built-in cloud provider enabled, and then later restart RKE2 with `--cloud-provider=rancher-vsphere`?

**Comment by braunsonm** [comment]
It's possible but I don't remember to be honest @brandond 

There was definitely some trial and error with that first setup, especially because RKE2 seems really finicky when initially bootstrapping (nodes don't like to join unless you restart them sometimes)

**Comment by brandond** [comment]
Interesting. QA is having a hard time reproducing the issue in the circumstances that I would expect it to occur.

**Comment by Jellyfrog** [comment]
@rancher-max Hi I'm seeing this error when I install a rke2 (v1.23.7+rke2r2) cluster on vsphere via rancher, I selected Cloud provider "none"
then install "vSphere CPI" helm-chart inside the cluster.
The daemonset fails to start the pods on the master nodes due to a collision with ` cloud-controller-manager`-pods:
`failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use `

, Im wondering if I should select "External" instead?

**Comment by rancher-max** [comment]
Hmm... What processes is it showing as listening on that port? `sudo netstat -tulpn | grep LISTEN | grep 10258`

**Comment by Jellyfrog** [comment]
@rancher-max I actually killed my test clusters, but I'll spin up a new and report back tomorrow :)

**Comment by Jellyfrog** [comment]
> Hmm... What processes is it showing as listening on that port? `sudo netstat -tulpn | grep LISTEN | grep 10258`

Master node:
```
# sudo netstat -tulpn | grep LISTEN | grep 10258
tcp        0      0 127.0.0.1:10258         0.0.0.0:*               LISTEN      5916/cloud-controll 
```

Worker node:
```
# sudo netstat -tulpn | grep LISTEN | grep 10258
tcp6       0      0 :::10258                :::*                    LISTEN      19515/vsphere-cloud 
```

**Comment by rancher-max** [comment]
Ah I think I see the issue. I'm surprised setting to "external" didn't help though in a fresh setup. Ref: https://github.com/rancher/rke2/blob/master/pkg/cli/cmds/root.go#L307-L319

Basically, to get the functionality you're after, I think you need to setup your config as one of the following:
```
cloud-provider-name: none
disable-cloud-controller: true
```
or
```
cloud-provider-name: external
```
or probably the best:
```
cloud-provider-name: rancher-vsphere
```
and then just customize helmchartconfig for different options.

**Comment by brandond** [comment]
Yeah, the recommended thing to do would be to deploy the packaged vsphere chart.

**Comment by kkmaslowski** [comment]
@rancher-max so is it possible to change cloud-provider to external on running cluster? If yes, how can I do that? I also installed cluster with default settings (Cloud provider = none) and I have port conflict with vsphere CPI (installed out-of-tree) and cloud-controller-manager.

**Comment by kkmaslowski** [comment]
@brandond @rancher-max If I want to install vsphere cpi and csi from Apps -> Charts  what should I set on servers and agents for cloud-provider-name? **cloud-provider-name: external** or **cloud-provider-name: none** or maybe **cloud-provider-name: none** with **disable-cloud-controller: true**?

**Comment by rancher-max** [comment]
Either your first or third option above, but you should know that the vsphere cpi/csi from Apps -> Charts is the same as what is packaged in RKE2 with `cloud-provider-name: rancher-vsphere` so it's still best to select that option for your cloud provider and just let it build upon startup.

**Comment by kkmaslowski** [comment]
So cloud-provider-name: `rancher-vsphere` installs vsphere cpi with vsphere csi? I thought it only installs vsphere cpi (cloud provider).

**Comment by brandond** [comment]
Yes and yes.

**Comment by carukc** [comment]
> So cloud-provider-name: `rancher-vsphere` installs vsphere cpi with vsphere csi? I thought it only installs vsphere cpi (cloud provider). And what about updates of both charts? Does it install latest version on every server startup?

What part of the YAML helm config file did you add 'disable-cloud-controller: true' to?

It does not seem to be working for us.

**Comment by brandond** [comment]
That goes in the RKE2 config file, not the helm values.

**Comment by carukc** [comment]
> That goes in the RKE2 config file, not the helm values.

Thank you for responding @brandond 

In our case, it's a k3s cluster that we're trying to start.  RKE2 clusters work fine but it seems like we can only start a k3s cluster if we install the vSphere CPI app.  The CCM will not start but installing the CPI app seems to load something else that allowed a k3s cluster to start.

I suppose that another alternative might be to disable the internal vSphere CPI when we start the k3s cluster that Rancher is on and just use the CPI App.

What do you think?

Thanks Again

**Comment by brandond** [comment]
Same difference.

How exactly are you configuring k3s? Out of the box, with all the defaults, it should start up fine regardless of where you're using it. If you disable things, you may need to replace those things with something else before it will work properly.

**Comment by carukc** [comment]
Which k3s cluster do you mean?  The one that we've setup for Rancher or the new ones that we are trying to create?

The management cluster for Rancher we created 2 minimally configured Ubuntu 22.04 VMs and ran:

curl -sfL https://get.k3s.io | sh -s - server  \
   --datastore-endpoint="postgres://kubernetes:[kubernetes-password]@database-05.grunt:5432/kubernetes?sslmode=disable"
   
same for the second node with --token [server-token]
   
so, no special options but we are using Postgres to store the state of the cluster.

Rancher is installed as follows:

helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
# install and test cert-manager
helm repo add jetstack https://charts.jetstack.io/
kubectl create namespace cert-manager
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.12.0
  --set 'extraArgs={--dns01-recursive-nameservers-only,--dns01-recursive-nameservers=1.1.1.1:53}'
# install Rancher
helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.domain.com \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=me@domain.com \
  --set letsEncrypt.ingress.class=traefik
  
We can create an RKE2 cluster on vSphere 7 after specifying:
* credentials
* pool = pool1
* Machine Count = 3
* all roles
* Data Center = our vSphere Data Center
* Resource Pool = pool on local server in Data Center (we have several machines in different places)
* Data Store = data store on local resource pool
* Folder = none
* Host = local host in Data Center
* Instance Options: 2 CPS, 4096 Memory, 20GB disk, OS = linux, Deploy from template: Data Center, Template = ubuntu 20.04 cloud OVF generated template with test account and ssh server turned on so we can access to check progress.
* Network = Server Network (same as RKE2 network and same as Rancher)
* Basics: Kubernetes Version = RKE2 v1.26+rke2r1
* Provider = vSphere
* Container Network = calico
* Security = Default - RKE2 Embedded
* Services = all
* Add-On Config: vCenter Host = our vSphere host, Data Centers = our vSphere Data Center, our username and password
* Storage Class Name: default, vsphere-csi-sc
* Storage Policy Name = vsphere-rancher-magnolias (from vSphere config)
* no other settings


When we try to create a k3s cluster as follows:
* credentials (from the RKE2 install)
* pool = pool1
* Machine Count = 3
* all roles
* Data Center = our vSphere Data Center
* Resource Pool = pool on local server in Data Center (we have several machines in different places)
* Data Store = data store on local resource pool
* Folder = none
* Host = local host in Data Center
* Instance Options: 2 CPS, 4096 Memory, 20GB disk, OS = linux, Deploy from template: Data Center, Template = ubuntu 20.04 cloud OVF generated template with test account and ssh server turned on so we can access to check progress.
* Network = Server Network (same as RKE2 network and same as Rancher)
* Basics: Kubernetes Version = k3s 1.26.7+k3s1
* Services = all
* Add-On Config - empty, no options available
* no other settings are available

It gets to: 'Configuring bootstrap node(s) test-k3s-3-pool1-774cc549f-qqn86: waiting for agent to check in and apply initial plan' and sits there for days.

The nodes are created in vSphere.  In Rancher, the first node is: 'Waiting for agent to check in and apply initial plan'
 
I've tried to figure out where to look for logs on the VMs but have not had much luck.  I somehow managed to create a cluster once.  I think that it was with the external vSphere CPI (1.5.100) installed but I can not recall what the state of the system was when it worked.

I've also noticed that when the k3s clusters fail to complete, I can no longer create RKE2 clusters.

So... my best guess is that something needs to happen on the VMs so that they are not succeeding in some part of the initilization but I'm not sure where to look.

I hope that answers your question.

**Comment by brandond** [comment]
> We can create an RKE2 cluster on vSphere 7 after specifying:
> When we try to create a k3s cluster as follows:
> It gets to: 'Configuring bootstrap node(s) test-k3s-3-pool1-774cc549f-qqn86: waiting for agent to check in and apply initial plan' and sits there for days.

Ah OK, that's the source of my confusion. You're asking about K3s in the RKE2 repo.

RKE2 bundles the rancher-vsphere chart, which handles the cloud-provider functionality that allows the cluster to complete provisioning when using the vsphere cloud provider.

K3s does not include any cloud-providers, other than the built-in stub cloud provider. If you want to use vsphere on K3s, you must disable the built-in cloud provider, and manually deploy the rancher-vsphere charts, or the upstream vsphere  charts. The suggested method to do this is to provide appropriately configured HelmChart resources in the additional manifests section of the UI. Unfortunately I don't have an example config available.

**Comment by carukc** [comment]
Thanks Brandon,

When you say 'disable the built-in cloud provider' do you mean start the k3s cluster that Rancher is installed on using the startup option: --disable-cloud-controller flag?

OK.. I'll check the versions on the upstreamand Rancher charts and try the most up to date.  Does that make sense?

Do these charts allow me to spinup k3s and RKE2 clusters on vSphere?

If I can get it working, I'll gladly send an example config to you :)

Thanks again

**Comment by a-blender** [comment]
@brandond I'm seeing this bug again with the vSphere CPI chart deployed onto an RKE2 cluster on the latest rancher 2.7 (2.7.9). It appears that the rke2-cloud-provider wasn't automatically disabled for me for some reason.

```
2023-11-20T17:50:59.768773728Z I1120 17:50:59.768655       1 serving.go:348] Generated self-signed cert in-memory
2023-11-20T17:50:59.768864605Z W1120 17:50:59.768791       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023-11-20T17:50:59.771196911Z failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use
```

Am I missing a step here? Do I need a manual install?

**Comment by brandond** [comment]
We haven't changed any of the RKE2-side logic for this in ages. Did you select vsphere as the cloud provider when deploying the cluster, or did you just deploy the vsphere chart from the app catalog after the cluster was already provisioned?

**Comment by a-blender** [comment]
Got it, I investigated and see the RKE2 logic has your fix. No, I just deployed CPI from the app catalog.

**Comment by brandond** [comment]
That is expected. There is no logic on the RKE2 side to disable things after the fact if a chart is deployed by the user; in fact we don't really recommend using the app catalog cloud provider charts with RKE2 at all. The user should select the correct cloud provider when provisioning the cluster.

**Comment by a-blender** [comment]
Ah - wondering if there's any plans to add a warning label to the UI saying using cloud provider charts from the app catalog is not recommend on RKE2 clusters? So I just needed to deploy the cluster with `cloud-provider=vsphere` or edit the cluster yaml in my case to fix it?

**Comment by brandond** [comment]
> any plans to add a warning label to the UI saying using cloud provider charts from the app catalog is not recommend on RKE2 clusters

I haven't heard of any plans to do that, but it would be a nice enhancement.

> deploy the cluster with cloud-provider=vsphere or edit the cluster yaml

Changing the cloud provider after the fact isn't supported, as node provider-ids are set when the node joins the cluster and immutable afterwards. The cluster should either be deployed without a cloud-provider and one added immediately (preferably via HelmChart user manifest), or better yet deployed with the correct one selected initially.

**Comment by a-blender** [comment]
Ok thank you!
