### ISSUE TITLE
Stop hosting Helm Chart tarballs in HelmChart resource manifests

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#224]
Currently, Helm chart tarballs for the packaged components are pulled down from the rke2-charts repos, base64-encoded, and inserted into the HelmChart resources chartContent fields for use at runtime. This complicates the build process, and abuses the Kubernetes datastore to hold large binary blobs.

We should instead use apiserver-hosted /static/ folder functionality [like we do  in k3s](https://github.com/rancher/k3s/blob/master/manifests/traefik.yaml#L7).

**Comment by davidnuzik** [comment]
Related: https://github.com/rancher/rke2/issues/171

**Comment by tallaxes** [comment]
> I can't actually download the file from the apiserver, so we may be missing the route for static files in rke2, but some of the plumbing is at least there.

Would that be because `/static` etc. is served by rke2 server, which (unlike in k3s) is now running in a separate process and on a different port (9345)? `curl https://<server>:9345/static/<artifact>` works ...

In HelmCharts with spec.bootstrap=true, `chart: https://localhost:9345/static/<chart>.tgz` works as well, since bootstrap [forces](https://github.com/k3s-io/helm-controller/blob/4ed68f1ecd2ba59cdf5090fb2c166f7055f8cf99/pkg/helm/controller.go#L273-L304) helm-install Job to run on server with hostNetwork. (Note that bootstrap=true also forces `KUBERNETES_SERVICE_HOST` to localhost, and `KUBERNETES_SERVICE_PORT` to 6443 ...) This would break if rke2 server bind-address is set to specific interface (instead of 0.0.0.0), but otherwise might be the way to do it. 

The separate process/port change also breaks [this kind](https://github.com/k3s-io/k3s/blob/c5aad1b5ed4e877eb7ed40f7c5910a83216f983c/manifests/traefik.yaml#L7) of `%{KUBERNETES_API}%` use, [supported](https://github.com/k3s-io/klipper-helm/blob/b02c0ea3966af09b4bf0b490a94438f340bf417e/entry#L97) by klipper-helm; would be nice to generalize. There does not appear to be a Service (and Endpoints) fronting rke2 servers, the way there is one fronting Kubernetes API, but maybe those can be engineered ...

**Comment by Martin-Weiss** [comment]
Quick question on this topic.. we have helm charts on a central server using a self-signed certificate. Now it seems that the job does not fetch the tgz due to missing trust to certificates from that self-signed CA. Do I miss the point where I can specify which CA to trust for helm chart pull?

**Comment by Martin-Weiss** [comment]
When using "static" and in case we are using a "load balancer" in front of :9345 - we must copy the helm charts to all masters/servers - is this the "plan"?

**Comment by brandond** [comment]
For manifests, either only one server should have a copy, or all servers should have the same content.

For static chart content, all servers should have it since non-bootstrap chart deployment will pull from the cluster service vip, which could be served from any node running the apiserver.

**Comment by Martin-Weiss** [comment]
> For manifests, either only one server should have a copy, or all servers should have the same content.
> 
> For static chart content, all servers should have it since non-bootstrap chart deployment will pull from the kubernetes cluster service vip, which could be served from any node running the apiserver.

Thanks - so from an architecture point of view we might need a sync process for the static content between servers/masters or better have the store for helm charts „outside“ of the clusters i.e. on a web-server or on a registry that is required anyway.. (similar to DNS / NTP - we need some infrastructure services outside and shared between clusters..)

So we might come back to the point that we need an easy way to trust self-signed certificates during the helm install so that we can fetch them from „everywhere“. I assume the best way might be it „inject / trust“ the CAs trusted on the host and also ensure the host trusts the kubernetes CA... (instead of just injecting the kubernetes CA into the helm install container as trusted..) - Background - during OS deployment we have to add „trusted CAs“ to the OS side of things anyway...

**Comment by brandond** [comment]
There's a PR out there to improve handling of manifests that are out of sync across nodes, but I haven't had a chance to clean it up and get it merged following a couple rounds of feedback - see k3s-io/k3s#2169. This doesn't address static content though.

For the helm chart repo cert stuff discussed in #736, you might update that issue to discuss your use case a bit more. I would probably lean towards allowing users to load certificates into a ConfigMap, passing that ConfigMap name into a field on the HelmChart CRD, and then importing certs from it into the container trust store at runtime. Exposing the host trust store to the pod may seem easier at first glance, but there is too much variability in where distros store their CA bundles.

**Comment by olljanat** [comment]
> FYI, it looks like rke2 still drops the k3s traefik chart at `/var/lib/rancher/rke2/server/static/traefik-1.81.0.tgz` since there's no functionality to prevent this from being compiled in, nor any option to disable dropping static files.

@brandond little bit side question but I wonder that is there some specific reason that why RKE2 is using NGINX instead of Traefik? Wouldn't it to be easier for everyone just support one option? (as after all RKE2 reuse a lot of code from K3s)

**Comment by brandond** [comment]
We're probably not going to change this, it's been working OK so far, and most of my complaints around the build process have been addressed.
