### ISSUE TITLE
[Release-1.20] etcd-snapshot loading config fails with "flag provided but not defined: -cluster-cidr"

### ISSUE THREAD

**Issue by VestigeJ** [rancher/rke2#2341]
**Environmental Info:**
RKE2 Version: 

$ sudo rke2 -v

```
rke2 version v1.20.13+rke2r1 (4b4a2d2919cf9dec39edc96014a319a077cc49cf)
go version go1.16.10b7

```
As well as present on 
$ rke2 -v

```
rke2 version v1.20.14-rc1+rke2r2 (6089937893fbb8da80494a594f7bced6b9ac5f15)
go version go1.16.10b7
```
Node(s) CPU architecture, OS, and Version: 

$ uname -a
```
Linux ip-172-31-22-27 5.11.0-1020-aws #21~20.04.2-Ubuntu SMP Fri Oct 1 13:03:59 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

$ kubectl get nodes

```
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-18-75    Ready    <none>                      65m   v1.20.14+rke2r2
ip-172-31-19-87    Ready    control-plane,etcd,master   66m   v1.20.14+rke2r2
ip-172-31-22-27    Ready    control-plane,etcd,master   69m   v1.20.14+rke2r2
ip-172-31-29-176   Ready    control-plane,etcd,master   65m   v1.20.14+rke2r2
```

$ kubectl get nodes

```
NAME              STATUS   ROLES                       AGE   VERSION
ip-172-31-26-58   Ready    control-plane,etcd,master   15m   v1.20.13+rke2r1
```
**Describe the bug:**

$ sudo rke2 --debug etcd-snapshot
```
Incorrect Usage: flag provided but not defined: -cluster-cidr
```

**Steps To Reproduce:**

$ sudo cat /etc/rancher/rke2/config.yaml 

```
debug: true
etcd-s3: true
etcd-s3-bucket: "justin-validation-bucket"
etcd-s3-region: "us-north-9"
etcd-s3-endpoint: "s3.us-north-9.amazonaws.com"
etcd-s3-access-key: "candyDISTANCEstriking"
etcd-s3-secret-key: "strikingDISTANCEcandy"
cluster-cidr: "9.9.0.0/16"
service-cidr: "9.8.0.0/16"
```
- Installed RKE2: 
both versions on different clusters, deployed the nodeport.yaml svc (successfully used the configured cidr block)
**Expected behavior:**

I intended to take a snapshot before deploying more workloads to revert away from. However a previous issue seems to have not been solved or tested by me fully. ```FATA[0000] flag provided but not defined: -cluster-cidr ``` 
**Actual behavior:**

CLI returned a fatal error flag from the config.yaml that isn't related to the task it was running. 
**Additional context / logs:**

https://github.com/rancher/rke2/issues/2130

**Comment by brandond** [comment]
I suspect that this is because of the --debug flag being before the etcd-snapshot command. The config loader looks at the arg string and appends the config args after the first unrecognized argument; putting the --debug flag first would cause it to add the config flags before the subcommands, which isn't a valid place for them.

cc @dereknola

**Comment by dereknola** [comment]
That is correct, there are two things to note on your commands:
1) --debug is a flag and thus should be placed after any subcommand, i.e. after the `etcd-snapshot`. That would fix your issue.
2) Since you have `debug: true` in your `config.yaml` you don't need to include the --debug in the command at all. 

That being said your issue has unearthed an undiscovered bug: `etcd-snapshot` is not correctly outputting debug logs even when `--debug` is provided. I will be opening a new issue to track that.
