### ISSUE TITLE
systemctl not stopping rke2 - Ubuntu 20.02.03

### ISSUE THREAD

**Issue by vtrenton** [rancher/rke2#2403]
**Environmental Info:**
RKE2 Version: 1.22.5+rke2r1

Node(s) CPU architecture, OS, and Version: x86

Cluster Configuration: Single/Multinode

**Describe the bug:**

when stopping the rke2-server daemon using systemctl stop rke2-server the daemon enters a failed state and does not stop the rke2 service. Currently confirmed on Ubuntu 20.04.03
**Steps To Reproduce:**

- log into a node running rke2-server
- run systemctl stop rke2-server.service on the node
- note the state will be 'failed' instead of the expected 'stopped' state.
- ps aux will show rke2 services such as kube-apiserver, kube-proxy and kube-controller-manager still running on the node.

**Expected behavior:**

rke2 will kill and stop all of the related services and enter the expected state of 'stopped' instead of failed.

**Additional context / logs:**

found a temp workaround to be the rke2-killall script. which doesnt fix the unit error but stops the  services.

**Comment by brandond** [comment]
> ps aux will show rke2 services such as kube-apiserver, kube-proxy and kube-controller-manager still running on the node.

As discussed on slack, stopping the service is only intended to stop the main rke2 process, the kubelet, and containerd. Workloads remain running in order to allow for nondisruptive upgrades.

This behavior is also consistent with k3s. In order to stop pod processes, including the static pod control-plane components, the killall script must be used.

**Comment by vtrenton** [comment]
closing as per Brad's explanation.
