### ISSUE TITLE
Gracefully stop container before shutdown/reboot 

### ISSUE THREAD

**Issue by Krumbelfix** [rancher/rke2#2411]
**Is your feature request related to a problem? Please describe.**
While rebooting our Servers with rke2 we had several times the issue that the containers did not stop properly and therefore the filesystem could not be unmounted. The server hung for several minutes before rebooting.
![RKE2_process_hang](https://user-images.githubusercontent.com/8148917/151528848-7da4e9fa-9ae6-43a6-ad47-a5901fe997ff.png)

**Describe the solution you'd like**
we implemented the attached systemd unit
[systemd-unit.txt](https://github.com/rancher/rke2/files/7957717/systemd-unit.txt)

**Describe alternatives you've considered**
A nice fix to speedup the server reboot provided by rke2 :)

**Comment by Martin-Weiss** [comment]
+1

**Comment by brandond** [comment]
Linking this in to graceful node shutdown as discussed at https://github.com/k3s-io/k3s/discussions/4319 would probably be the proper way to go about this.

**Comment by brandond** [comment]
I am not confident that this is something that RKE2 should provide for itself. Both K3s and RKE2 do not - by design - stop workload pods when shutting down. There is some discussion in the linked K3s issue about possible approaches that Harvester (or other users of K3s/RKE2) could take to ensuring that workloads are explicitly terminated as part of systemd shutdown. It could even just be something as simple as installing a service that runs the rke2-killall.sh script on shutdown:

```
# /etc/systemd/system/rke2-cleanup.service
[Unit]
Description=rke2-cleanup
DefaultDependencies=no
Before=shutdown.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/rke2-killall.sh
TimeoutStartSec=0

[Install]
WantedBy=shutdown.target
```

**Comment by Krumbelfix** [comment]
In my opinion it should be bundled since it improves the rke experience. It does not have any disadvantages in the daily business and is helps keeping it easy.

**Comment by alancaldelas** [comment]
Was this actually resolved? I ran the kill-all and now my ceph pods are in unknown state
