### ISSUE TITLE
EOM/EOL Policies

### ISSUE THREAD

**Issue by FernandoBenayas** [rancher/rke2#2419]
Hello! 
I'm part of a team which is trying to convince our company to start using RKE2 as a secured solution for implementing Kubernetes clusters. Most concerns regarding security have been met, but many people in our security and maintenance departments are raising doubts regarding RKE2's support policies. This is discussed in length down below.
 
Since we didn't find any contact information in your web page, we have decided to raise this Issue to get in contact with you.

### **Is your feature request related to a problem? Please describe.**
We had a hard time trying to find support-related information about RKE2. We would like to ask for information regarding the following issues related to support:
1. Are there any **End-Of-Maintenance** - **End-Of-Life** policies in place for versions being actively maintained?
2. Is there any **formal patching process**? We assumed that the upgrade process described in https://docs.rke2.io/upgrade/upgrade/ is the "formal patching process" we were looking for (and that every patch is designed to be applied following this process), but we would like some confirmation on that.
3. Is there a way to get in contact with you in case that we have any other doubt regarding support?

If there is a "commercial-only" version of RKE2 which provides support in exchange for a subscription fee **we are open to consider such subscription**, but first we would like to know the details of such support.

### **Describe the solution you'd like**
Answers to the questions listed in the previous section and some contact information in RKE2's web page.

### **Describe alternatives you've considered**
Other teams in our company are proposing other Kubernetes engines, or just migrating to Kubernetes in Azure Government.

**Comment by pmckeithSUSE** [comment]
Hi Fernando,
RKE2, RKE, & K3s support is available and included with a subscription to Rancher (the product). That is why you are having trouble finding explicit information on RKE2 only. If you are in the USA, let me know and I can put you in touch with the right person. Otherwise go to this web page [1] and use the chat or "Request a call" option at the bottom of the page. This way you will get routed to the correct person in your region to help answer ALL your questions. 

BTW, you do not need a different "commercial version", just a support subscription that will address all the concerns of your security team and more. Otherwise they are correct in that you would be limited to the "support" the community is willing to provide. Great for learning, developing, not so great for high security production workloads. 

[1] https://www.suse.com/support/?id=SUSE_Rancher_Kubernetes_Management#subscription-details
Thanks for your support!
-Paul

**Comment by FernandoBenayas** [comment]
Hello Paul!

Thank you very much for your quick and thorough response. We will get in contact with the SUSE support team as soon as we can so we can confirm that RKE2 is the right choice for us ( I hope :) ).

Thanks!

**Comment by pmckeithSUSE** [comment]
Hi Fernando,
Did you get what you needed?

-Paul
