### ISSUE TITLE
server kube-proxy-arg not propagated to agents pod-manifests

### ISSUE THREAD

**Issue by pyaillet** [rancher/rke2#2514]
Thanks for making rke2 !

**Environmental Info:**
RKE2 Version: 
```
# rke2 -v
rke2 version v1.22.4+rke2r2 (3961b9e78a7bc116d7662bfbb7d8472d85e0cbb7)
go version go1.16.10b7
```

Node(s) CPU architecture, OS, and Version: 
```
# uname -a
Linux test-kube-proxy-master0 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 server, 1 agent to reproduce the issue

**Describe the bug:**
The server flag `kube-proxy-arg` is not propagated to agents.

**Steps To Reproduce:**
Deploy a rke2 cluster with the following flag:
```
kube-proxy-arg:
- --metrics-bind-address=0.0.0.0:10249
```

**Expected behavior:**
The option should be set on both servers and agents:
```
# grep metrics-bind-address /var/lib/rancher/rke2/agent/pod-manifests/kube-proxy.yaml
    - --metrics-bind-address=0.0.0.0:10249
```

**Actual behavior:**
The option is not set on agents:
```
# grep metrics-bind-address /var/lib/rancher/rke2/agent/pod-manifests/kube-proxy.yaml
```

**Comment by brandond** [comment]
All of the args (kube-proxy-arg, kubelet-arg, etc) are intentionally not propagated downstream from servers to agents to allow for node-specific customization. Cluster global settings (CIDRs, CNI selection, etc) are propagated.

At one point the kube-proxy args were set via a helm chart and it caused a number of problems due to lack of per-node customizability, see:
* https://github.com/rancher/rke2/issues/751

**Comment by pyaillet** [comment]
Thanks for the quick answer ! I did not think it was possible to pass the option to the agent because of the doc.
I opened a PR to fix this.

Let me know if this is ok for you or if it needs any changes.

Anyway thanks in advance for your time :)
