### ISSUE TITLE
[Release 1.21] masquerade NAT rules remain after uninstall

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#2626]
Backport: https://github.com/rancher/rke2/issues/2599

**Comment by rancher-max** [comment]
Reopening because this does not work when doing an upgrade from v1.22.7+rke2r1 to v1.22.8-rc5+rke2r1. Checked using SLES 15 SP3.

**Comment by bguzman-3pillar** [comment]
Validated using commit: 1aac0eb9103fcbfd8eccba1e3f6b1d23b51b1964

Once Installed RKE2 I ran `sudo rke2-uninstall.sh` to uninstall.
After that check with `sudo iptables-save |grep -i masq` 

Expected behavior: don't see lines with 
`-A POSTROUTING -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully`

Actual: uninstall has removed the entries correctly.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/95362932/163020004-2d5f5d1d-e974-4cfa-a6de-9a0d90d6d90c.png">

**Comment by manuelbuil** [comment]
Actually, a good idea would be to verify that the tables still exist after running rke2-uninstall.sh. And then they are removed completely when executing those commands manually
