### ISSUE TITLE
Enable dual-stack config for Cilium automatically

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#2741]
**Is your feature request related to a problem? Please describe.**

Unlike Cilium, Calico and canal don't need the user to enable anything manually to run dual-stack. Enabling dual-stack config automatically provides a better user experience and aligns all supported CNI plugins. 

**Describe the solution you'd like**

Cilium should enable all ipv6 config as soon as it detects a dual-stack pod-cidr

**Describe alternatives you've considered**

Leaving it as today. It requires manual intervention from user to enable the ipv6 config

**Additional context**

**Comment by manuelbuil** [comment]
To verify this, deploy rke2+cilium with dual-stack config (cluster-cidr and service-cidr) and pods should get two ips per interface (ipv4 + ipv6). Before, it was needed to manually configure "ipv6.enable: true" in the values of the helm chart

**Comment by rancher-max** [comment]
In addition to what Manuel mentioned above, we should also ensure:
1. There are no changes when only using ipv4
2. Upgrading a dualstack cilium configuration that already had these values configured in the helmchart is successful

**Comment by rancher-max** [comment]
### Validated using master branch commitid `3822a59026cafb91323b551176abd40453423a9e`

#### Upgrade Scenario
1. Initially deployed using v1.23.5+rke2r1 with the following config:
```
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
cni: cilium
node-ip: <redacted ipv4>,<redacted ipv6>
node-external-ip: <redacted ipv4>,<redacted ipv6>
```
2. Deployed ipv4 and ipv6 services and could not access the ipv6 endpoint because I had not configured the helmchart properly.
3. Reinstalled with the same config and with the following HelmChartConfig:
```
# Located at /var/lib/rancher/rke2/server/manifests/cilium-values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    ipv6:
      enabled: true
```
4. Deployed ipv4 and ipv6 services using `kubectl apply -f https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml` and saw success from both the ipv6 and ipv4 endpoints
5. Upgraded setup to master commit `3822a59026cafb91323b551176abd40453423a9e` 
6. The already deployed services continued to be successful
7. Deployed new ipv6 services with ingress and all of that was queryable and working as expected

#### Fresh Install Scenario
1. Deployed using master commit `3822a59026cafb91323b551176abd40453423a9e` with the following config:
```
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
cni: cilium
node-ip: <redacted ipv4>,<redacted ipv6>
node-external-ip: <redacted ipv4>,<redacted ipv6>
```
2. Deployed ipv4 and ipv6 services using `kubectl apply -f https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml` and saw success from both the ipv6 and ipv4 endpoints

#### IPv4 Only Scenario
1. Deployed using master commit `3822a59026cafb91323b551176abd40453423a9e` with the following config:
```
cni: cilium
node-external-ip: <redacted ipv4>
```
2. Deployed ipv4 and ipv6 services using `kubectl apply -f https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml` and saw success from ONLY the ipv4 endpoints. In fact, it correctly reported that the cluster is not using dualstack: `Error from server (Invalid): error when creating "https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml": Service "my-service-require-dual" is invalid: spec.ipFamilyPolicy: Invalid value: "RequireDualStack": this cluster is not configured for dual-stack services`
