### ISSUE TITLE
[Release 1.21] Enable dual-stack config for Cilium automatically

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#2747]
Backport: https://github.com/rancher/rke2/issues/2741

**Comment by mdrahman-suse** [comment]
# Validated in rke2 with release 1.21 RC v1.21.12-rc2+rke2r1 

Ref: https://github.com/rancher/rke2/issues/2741#issuecomment-1104514561

# Upgrade scenario

- Installed rke2 v1.21.11+rke2r1 with the config below
```
write-kubeconfig-mode: 644
token: secret
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
cni: cilium
node-ip: <redacted_privateipv4>,<redacted_ipv6>
node-external-ip: <redacted_ipv4>,<redacted_ipv6>
```
- Deploy dual stack service using `kubectl apply -f https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml`
- Curl both ipv4 and ipv6 ip's (use `kubectl get svc`) and verified ONLY ipv4 returns response
- Upgrade rke2 with v1.21.12-rc2+rke2r1
- Reboot the instance/ restart rke2 service (check Note)
- Curl both ipv4 and ipv6 ip's and verify BOTH the ip's return response
NOTE: need confirmation from @manuelbuil on the expected behavior after the upgrade as it was observed that sometimes it works on rebooting the instance and sometimes on restarting rke2 service CC: @rancher-max 

# Fresh install scenario

- Install rke2 v1.21.12-rc2+rke2r1 with the config below
```
write-kubeconfig-mode: 644
token: secret
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
cni: cilium
node-ip: <redacted_privateipv4>,<redacted_ipv6>
node-external-ip: <redacted_ipv4>,<redacted_ipv6>
```
- Deploy dual stack service using `kubectl apply -f https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml`
- Curl both ipv4 and ipv6 ip's (use `kubectl get svc`) and verified BOTH ipv4 and ipv6 returns response

# Fresh install only ipv4

- Install rke2 v1.21.12-rc2+rke2r1 with the config below
```
write-kubeconfig-mode: 644
token: secret
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
cni: cilium
node-ip: <redacted_privateipv4>,<redacted_ipv6>
node-external-ip: <redacted_ipv4>,<redacted_ipv6>
```
- Deploy dual stack service using `kubectl apply -f https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml`
- Observed the error below
```
Error from server (Invalid): error when creating "https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml": Service "my-service-v6" is invalid: spec.ipFamilies[0]: Invalid value: []string(nil): ipfamily IPv6 is not configured on cluster
Error from server (Invalid): error when creating "https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml": Service "my-service-require-dual" is invalid: spec.ipFamilyPolicy: Invalid value: "RequireDualStack": Cluster is not configured for dual stack services
```
