### ISSUE TITLE
Create user with X509 certificate doesn't work "error: You must be logged in to the server (Unauthorized)"

### ISSUE THREAD

**Issue by luis13byte** [rancher/rke2#2793]
**Environmental Info:**
RKE2 Version: v1.22.8+rke2r1

**Steps To Reproduce:**
- Installed RKE2
- Execute the following script (create user with certificate):

~~~
#!/bin/bash

USER="luis13byte"
CLUSTERCERTS="/var/lib/rancher/rke2/server/tls/"
CLUSTERNAME="default"

echo "Creating User certs and config.."
mkdir ${USER}/ && cd ${USER}/
openssl genrsa -out ${USER}.key 2048

openssl req -new -key ${USER}.key \
  -out ${USER}.csr \
  -subj "/CN=${USER}/O=IT}"

# Signing csr with the Master CA and key of the cluster
openssl x509 -req -in ${USER}.csr \
  -CA ${CLUSTERCERTS}server-ca.crt \
  -CAkey ${CLUSTERCERTS}server-ca.key \
  -CAcreateserial \
  -out ${USER}.crt -days 500

kubectl config set-credentials ${USER} \
  --client-certificate=${USER}.crt \
  --client-key=${USER}.key --embed-certs

kubectl config set-context ${USER}-context \
  --cluster=${CLUSTERNAME} --user=${USER}
~~~

**Expected behavior:**
Unless the kube-apiserver interprets that a user without roles is logging in.

**Actual behavior:**
~~~
root@controlplane1:~# kubectl get pods # for example
error: You must be logged in to the server (Unauthorized)
~~~

Is it possible that the certificates with which the CSR is being signed are not correct? There is little documentation on this and thanks for the help.

To make sure I have confirmed that server-ca.crt has the same certificate as what I can see "live" with kubectl commands.

~~~
kubectl config view -o jsonpath='{.clusters[0].cluster.certificate-authority-data}' --raw | base64 --decode
~~~

**Comment by brandond** [comment]
1. You're using the server CA to sign client certificates. You should use the client CA instead.
2. The CN on the certificate determines the username for the certificate; the OU determines the group. You'll need to have RBAC that binds roles to the user/group you put on the certificate.
3. I would encourage you to use the Kubernetes Certificate Signing workflow to provision your certs, instead of just directly using openssl to create certs from the CAs on disk.
  https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/

**Comment by luis13byte** [comment]
Thank you very much @brandond  using the Kubernetes certificate signing workflow I didn't even need to specify the CA to sign client certificates with. 

I now have a user that can authenticate against the API, I mark this as solved.
