### ISSUE TITLE
RPM-based install results in a different systemd service name than rke2-installer.run

### ISSUE THREAD

**Issue by bgulla** [rancher/rke2#295]
os: CentOS Linux release 7.8.2003 (Core)
kernel:  3.10.0-1127.el7.x86_64
version: rke2-beta16

It would seem that the systemd service that is installed differs based on the installation method. RPM-based installs registers as `rke2-server` where the self-installer registers a `rke2` service. 
 

`rke2-installer.run` -> `/usr/local/lib/systemd/system/rke2.service`
`rke2-server.rpm` -> `(/usr/lib/systemd/system/rke2-server.service`

**Comment by dweomer** [comment]
This was intentional on my part. My reasoning:
- Naming the systemd service by the role it plays reeks. When on a host I need to know what role it plays in the larger cluster before I can inspect the service that defines the hosts participation in said cluster? No, this is a flaw with the RPM installer(s) in my opinion.

Would like a design discussion with @Oats87 about this.

**Comment by dweomer** [comment]
> we did not want to run into conflicting unit files when you try to install both RPM's, which was a desired capability.

@Oats87 I understand everything up until this statement. Under what scenario would one want two services installed on a host that leverage content on the filesystem that is largely overlapping and cannot be run at the same time?

**Comment by cjellick** [comment]
We should discuss this today and come to a conclusion.

**Comment by davidnuzik** [comment]
RPM to have 2 different unit files for each server and agent. We will no longer capture env vars - user will need to use config file. Will need to add conflicts for each server and agent (if server running then cannot also run agent service, if agent service running then cannot also run server).

**Comment by cjellick** [comment]
@dweomer This is at least partially addressed, as per your references in the above prs. Is it fully addressed and can be moved to test?
cc @davidnuzik - please follow up on this today

**Comment by ShylajaDevadiga** [comment]
Upgrade using SUC fails due to the location rke2 is running.
Upgrade from rke2 -v
rke2 version v1.18.8-beta19+rke2 to beta20
```
system-upgrade   apply-rke2-server-on-ip-172-31-15-79.us-east-2.compute.in-9p4ws      0/1     Error       0          2m44s
```
Logs:
```
kubectl logs -n system-upgrade apply-rke2-server-on-ip-172-31-15-79.us-east-2.compute.in-9p4ws
+ upgrade
+ get_rke2_process_info
+ grep -E '/usr/local/bin/rke2 .*(server|agent)'
+ ps -ef
+ grep -E -v '(init|grep)'
+ awk '{print $1}'
+ rke2_PID=
+ '[' -z  ]
+ fatal 'rke2 is not running on this server'
+ echo '[ERROR] ' 'rke2 is not running on this server'
[ERROR]  rke2 is not running on this server
+ exit 1
```
Failing due to rke2 binary is running in /usr/bin
```
ps -ef |grep rke2 |grep server
root     10461     1  0 16:55 ?        00:00:19 /usr/bin/rke2 server
```

**Comment by cjellick** [comment]
@ShylajaDevadiga it is unclear if you are doing an RPM install or a tar based one (though I can deduce from the location of the binary that its rpm).

What you found is a valid bug, but I want to help clarify what was done as part of this:
The tarball-based install was changed to match RPM. When you install via tarball or via rpm. the services should be rke2-server and rke2-agent.

Regarding @davidnuzik comment:
> (From 9/11/20 Design call) RPM to have 2 different unit files for each server and agent. We will no longer capture env vars - user will need to use config file. Will need to add conflicts for each server and agent (if server running then cannot also run agent service, if agent service running then cannot also run server).

Here is the current state of things:

1. Both RPM and tarball should install units called rke2-server and rke2-agent
2. For both, env vars are no longer captured and forwarded to the rke2 process. Env vars starting with `INSTALL_RKE2_...` are still respected because they are specific the install script, but any env vars starting with `RKE2_...` have no effect and are not respected.
3. The tarball install DOES make rke2-server and rke2-agent conflict at the systemd unit level, but RPM DOES NOT. I have opened this issue to track that: https://github.com/rancher/rke2/issues/360.

Can you spin your above comment about not being able to use SUC with RPM installs into a separate issue? I may descope the ability to upgrade RPM installs with SUC. May require that you upgrade via yum (or the script, which does yum).

**Comment by ShylajaDevadiga** [comment]
Tracking above SUC issue separately here #359 

Validated tarball install as well as rpm installs registers a rke2 service in a common location
And we have 2 different unit files for each server and agent


```
sudo INSTALL_RKE2_VERSION=v1.18.8-beta20+rke2 sh ./install.sh
Updating Subscription Management repositories.
Rancher RKE2 Common (testing)                                                                                                                            1.9 kB/s | 1.3 kB     00:00    
Rancher RKE2 1.18 (testing)       
...
sudo systemctl enable rke2-server
Created symlink /etc/systemd/system/multi-user.target.wants/rke2-server.service → /usr/local/lib/systemd/system/rke2-server.service

sudo systemctl enable rke2-agent
Created symlink /etc/systemd/system/multi-user.target.wants/rke2-agent.service → /usr/lib/systemd/system/rke2-agent.service.
```
Tarball install:
```
sudo INSTALL_RKE2_METHOD='tar' INSTALL_RKE2_VERSION=v1.18.8-beta20+rke2 sh ./install.sh
[INFO]  using v1.18.8-beta20+rke2 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.18.8-beta20+rke2/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.18.8-beta20+rke2/rke2.linux-amd64.tar.gz
[INFO]  verifying installer
[INFO]  unpacking tarball file
ubuntu@ip-172-31-3-194:~$ sudo systemctl enable rke2-server
Created symlink /etc/systemd/system/multi-user.target.wants/rke2-server.service → /usr/local/lib/systemd/system/rke2-server.service
```

**Comment by ShylajaDevadiga** [comment]
Sorry, Found a discrepency above with rpm being sym linked to /usr/lib/ and tarball to /usr/local/lib/

**Comment by ShylajaDevadiga** [comment]
Tracked separately #355 Closing as validated.
