### ISSUE TITLE
[QUESTION] How do I pass kubelet argument --node-ip

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rke2#3105]
as every node have it's own IP I can't hard code that in cluster configuration in `machineGlobalConfig`
I've tried this: 
```
...
rkeConfig:
...
  machineGlobalConfig:
    kubelet-arg:
      - node-ip=$(ec2metadata --local-ipv4)
```

but this is not evaluated and kubelet process is spawned with `--node-ip=$(ec2metadata --local-ipv4)` argument

**Comment by riuvshyn** [comment]
@brandond any idea? 🙏🏽

**Comment by brandond** [comment]
RKE2 has a top-level `--node-ip` flag that is passed through to the kubelet, and is probably overriding your attempt to set the flag directly.. Have you tried just specifying the `node-ip` in the RKE2 config?

Also - are you using the built-in RKE2 cloud provider, or have you started rke2 with `--disable-cloud-provider` so that you can use the AWS cloud provider?

**Comment by riuvshyn** [comment]
replied in https://github.com/rancher/rke2/issues/3108#issuecomment-1167723416
I am using aws out-of-tree cloud provider and I have configured `cloud-provider-name: external`
I am also disabeld cloud controller `disable-cloud-controller: true`

**Comment by riuvshyn** [comment]
this https://github.com/rancher/rke2/issues/3108#issuecomment-1167732924 answers the question, ty @brandond
