### ISSUE TITLE
Windows Calico Configuration Fails with multiple Interfaces

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#3388]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:
1 Linux server + 1 windows Agent

**Describe the bug:**
If the windows node has multiple interfaces, Calico will always select the "first-found" even if that interface does not enable connectino to the rest of the cluster.

**Steps To Reproduce:**
Run the `mixedos` E2E test

**Expected behavior:**
Windows node should have the same Calico IP as the IP specified via `node-ip` or the IP that can connect to the server

**Actual behavior:**
Windows node selects the first interface in the list and ends up with a bad Calico IP
```
vagrant@server-0:~$ kubectl get nodes -o yaml | grep IPv4
      projectcalico.org/IPv4Address: 10.10.10.101/24
      projectcalico.org/IPv4Address: 10.10.10.100/24
      projectcalico.org/IPv4Address: 10.0.2.15/24 <=== NOTE THE INCORRECT NETWORK IP FOR THE WINDOWS NODE
```

**Additional context / logs:**

**Comment by rancher-max** [comment]
I'm going to close this as I'm struggling to repro this in cloud environments. This was found and validated via the e2e tests with vagrant, so that should be sufficient. It's worth noting that of all the options in https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.NodeAddressAutodetection at this time, the `kubernetes` key has not yet been added.
