### ISSUE TITLE
Node kube-apiserver failed to create listener: failed to listen on 0.0.0.0:6443

### ISSUE THREAD

**Issue by LuksJobs** [rancher/rke2#3480]
**Environmental Info:**

rke2 version v1.24.6+rke2r1 (473cc354adecd235f00f0d80828611b0556b83e5)
go version go1.18.1b7

Node(s) CPU architecture, OS, and Version: 

Linux rancher-prd-01 4.15.0-194-generic #205-Ubuntu SMP Fri Sep 16 19:49:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

![alt text](https://i.imgur.com/jLNAKSv.png)

**Describe the bug:**

Workers node have these errors on kube-apiserver pod:

![alt text](https://i.imgur.com/8pLePSx.png)

**crashloopback error logs:**

`
Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
I1019 20:33:37.957778 1 server.go:565] external host was not specified, using 10.10.33.17
I1019 20:33:37.958213 1 server.go:172] Version: v1.23.9+rke2r1
E1019 20:33:37.958760 1 run.go:74] "command failed" err="failed to create listener: failed to listen on 0.0.0.0:6443: listen tcp 0.0.0.0:6443: bind: address already in use"
`

**Comment by brandond** [comment]
Given that the kube-apiserver pods in question are all running older versions of the hardened-kubernetes image, I suspect that this was caused by reusing nodes without cleaning them properly ahead of time, or by adding new nodes using a VM image that was previously running RKE2 as a server. If you're going to do either of these things, please make sure you're cleaning up the old installation properly beforehand.

**Comment by LuksJobs** [comment]
> ```shell
> systemctl start rke2-agent
> ```

@brandond Thank you very much! Accidentally it could be that I started the server on worker nodes 🥵
Following the commands you passed solved my problem.
