### ISSUE TITLE
SLE-BCI Image Audit

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#3564]
Ensure that we are using the new SLE bcibase images where appropriate. We need to audit at least all of the following locations:
- https://github.com/rancher/rke2
- https://github.com/rancher/rke2-charts
- https://github.com/rancher/rke2-upgrade
- https://github.com/rancher/rke2-selinux
- https://github.com/rancher/system-upgrade-controller
- Any charts that we use from https://github.com/rancher/charts

- All images from https://github.com/rancher/rke2/blob/master/developer-docs/image_sources.md

Many images from these repos come from multiple different locations. See https://github.com/rancher/rke2/issues/3260 for a reference.

**Comment by macedogm** [comment]
@rancher-max we can potentially leverage the Updatecli automation - [rancherlabs/updatecli-automation](https://github.com/rancherlabs/updatecli-automation) - for this, because it's easy to create an update pipeline with Updatecli to monitor multiple places to see if a certain image is up to date, for example. There is also a PR to add Updatecli to K3s - https://github.com/k3s-io/k3s/pull/6583.

**Comment by caroline-suse-rancher** [comment]
@briandowns Is this automation something the release crew could integrate?

**Comment by briandowns** [comment]
@caroline-suse-rancher Yes. We will take care of it.

**Comment by caroline-suse-rancher** [comment]
We are currently moving away from SLE BCI, so I will close this.
