### ISSUE TITLE
Support signing certs when using custom CA

### ISSUE THREAD

**Issue by QtSYnT** [rancher/rke2#3650]
**Is your feature request related to a problem? Please describe.**

Following the steps in #541 allows for custom certs to be provided. However, when using custom certs there is also a use case for including the full cert chain when dealing with multiple intermediary CAs. Including the cert chain requires you to specify a standalone signing cert in kube-controller-manager as it will error when provided the full cert chain. 

Example:
```
kube-controller-manager-arg:
  - cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/rke2/server/tls/client-ca-signing.crt
  - cluster-signing-kubelet-client-cert-file=/var/lib/rancher/rke2/server/tls/client-ca-signing.crt
  - cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/rke2/server/tls/server-ca-signing.crt
  - cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/rke2/server/tls/server-ca-signing.crt
```

The root of the problem is that when joining a control plane node, RKE2 is unaware of these signing certs and as a result they are not included in the bootstrap data so they must be manually copied to the node.

**Describe the solution you'd like**

Ideally RKE2 would have a way to include these in the bootstrap data so that they are replicated across nodes. Bonus points if on cluster creation RKE2 can detect that the provided CA certs contain the cert chain and automatically create/config the signing cert.

Failing this, a way to prevent RKE2 from overwriting the existing certs on a node so that we can take full control over what certs are being used on each node.

**Describe alternatives you've considered**

The non-ideal solution is to just copy these certs ourselves though this introduces some security implications on our end that RKE2 neatly solves with the current bootstrap method.

**Additional context**

**Comment by brandond** [comment]
There are several challenges around use of user-provided CAs, and around CA certificate renewal in general. This is currently being tracked under https://github.com/rancher/rke2/issues/541

**Comment by brandond** [comment]
I will also say that there are cases where you absolutely SHOULD NOT have a common root CA for all of your cluster CAs. There are cases where Kubernetes evaluates client authentication against a list of CA bundles in order to determine what type of authentication the client is using. If all of the client certificates and tokens can be validated using the same certificate chains, things will break in odd an unexpected ways. See the `sa.key` and `sa.pub` mentioned in https://kubernetes.io/docs/setup/best-practices/certificates/#single-root-ca

**Comment by Martin-Weiss** [comment]
> I will also say that there are cases where you absolutely SHOULD NOT have a common root CA for all of your cluster CAs. There are cases where Kubernetes evaluates client authentication against a list of CA bundles in order to determine what type of authentication the client is using. If all of the client certificates and tokens can be validated using the same certificate chains, things will break in odd an unexpected ways. See the `sa.key` and `sa.pub` mentioned in https://kubernetes.io/docs/setup/best-practices/certificates/#single-root-ca

@brandond - maybe I am missing something, here but the doc you linked explains the usage of a common root CA with intermediated CAs (single root ca) and I can not find the point that this SHOULD NOT be done.. can you share some more insights / details on why this will break something in odd and unexpected ways?

**Comment by brandond** [comment]
@Martin-Weiss the comment I'm looking for was buried somewhere in the Kubernetes source code and now I'm not finding it. I think the restriction was around the service account signing key and certificate. You don't actually need a cert, it is possible to sign and validate service account tokens with just a key, which is what we do. 

However, if you do use a certificate, it MUST NOT be signed by any other CA. The way the authentication chain works is that the request is checked by a sequence of authenticators. The first one that can validate the signature on the request is expected to also be able to extract the fields from the request. If the service account token's signature can be validated against any of the other cluster CAs, it will match the request too early in the chain, and fail to extract the fields because it is not being matched by the correct authenticator. This will cause all requests with service account tokens to be rejected.

**Comment by Martin-Weiss** [comment]
@brandond  - from my point of view we should not have multiple CAs / multiple root CAs.. At least the number of root CAs should be as low as possible. In case we need multiple CAs intermediate CAs should be used. 

Background is that the trust that needs to be established where ever the certificates need to be validated. 

We need to distribute the root CA as trusted to all clients and we need to manage the trusted CAs on the clients side of things.. the more CAs we have the less useful a CA is and the CAs are acting like single certificates.

And yes - a single certificate must never be signed my multiple CAs (not even sure if/how that would be possible). AFAIK it is always a linear chain rootCA - intermediateA - intermediateB - certificate. Please correct me if I am wrong in my understanding..

**Comment by brandond** [comment]
> from my point of view we should not have multiple CAs / multiple root CAs.. At least the number of root CAs should be as low as possible. In case we need multiple CAs intermediate CAs should be used.

Unfortunately this is not really the Kubernetes way of doing things. While kubernetes itself **can** be set up that way, Kubernetes and most Kubernetes-native applications are designed to support many individual roots of trust, with certificate distribution being baked into the platform via configmaps/secrets, and first-class support for configuring explicit CAs in client components.

**Comment by Martin-Weiss** [comment]
> > from my point of view we should not have multiple CAs / multiple root CAs.. At least the number of root CAs should be as low as possible. In case we need multiple CAs intermediate CAs should be used.
> 
> Unfortunately this is not really the Kubernetes way of doing things. While kubernetes itself **can** be set up that way, Kubernetes and most Kubernetes-native applications are designed to support many individual roots of trust, with certificate distribution being baked into the platform via configmaps/secrets, and first-class support for configuring explicit CAs in client components.
> 

It is good to support multiple different trusted CA bundles - but we also have to support using a single root CA with multiple intermediate.. if that "can" be done and is supported - all is fine.

> > a single certificate must never be signed my multiple CAs
> 
> In practice this is true, but you will occasionally find newer CAs distributing versions of their root or intermediates that are cross-signed by more mature CAs for older clients. This isn't really something we need to be concerned about though. In this case I was just talking about the service account signing key; if you use a cert with it, it needs to be either self-signed, or signed by a CA that is not shared with the client or server roots.

Ok - I do not get this completely - why is it required to be self-signed and not in a trust-chain? This is basically against the way how I understood the whole CA -> Cerificate thing so far..

**Comment by brandond** [comment]
> why is it required to be self-signed and not in a trust-chain

Because that's how it works. This cert is not used for TLS servers or clients, all it is used for is signing JWTs.

**Comment by Martin-Weiss** [comment]
> > why is it required to be self-signed and not in a trust-chain
> 
> Because that's how it works. This key is not used for TLS servers or clients, all it is used for is signing JWTs, which are validated by other components within the same cluster. Its possible that this has been improved since I last attempted to use an externally signed cert for service account signing, but I see that even in the current upstream docs it does not mention signing the cert with any of the CAs. It just says:
> 
> > On top of the above CAs, it is also necessary to get a public/private key pair for service account management, sa.key and sa.pub.
> 
> All they ask for is a key pair, not a cert.

Ok - so as long as there is no chain and these certs are not verified anywhere outside of the cluster - who cares.. it would just be a challenge in case these certs would need to be verified outside..

**Comment by QtSYnT** [comment]
@brandond This issue was only about the replacement of the following certs with our own intermediary certs:
- rke2-server-ca
- rke2-client-ca
- rke2-request-header-ca
- etcd-server-ca
- etcd-peer-ca

If rke2-server-ca and rke2-client-ca are intermediary certs then the full CA bundle needs to be included for the cluster to function.  When using a CA bundle kube-controller-manager will then require the intermediary CA without the full bundle to be passed as another argument in addition to the full CA bundle. This request was to include those required extra files in the bootstrap payload for joining control plane nodes.

Just wanted to make sure that the intent of this request was clear as service account tokens are still being signed exactly the same as default RKE2.

**Comment by Martin-Weiss** [comment]
As a side note - when using intermetiate CAs AFAIK the certificates need to include the "chain without the root CA" - is this the case in the expeted setup? (intermediate certs as part of server/service certs and only trust the root CA in the bundle)

**Comment by brandond** [comment]
@QtSYnT have you looked at the PR yet?

**Comment by QtSYnT** [comment]
Yup, that PR has exactly what I was looking for. Didn't realize you already had something for it, thanks!

**Comment by Martin-Weiss** [comment]
@brandond - thanks for the info! I am not deep enough in this from a kubernetes point of view but it looks a bit like a "missing feature in the design" in case we rely on using different Certificate Authorities.. 
And it is also strange that this depends on "CN=" where "CN=" is depreacted and we should only use SANs instead.. but maybe I am mixing up things..

**Comment by brandond** [comment]
@Martin-Weiss yes, I've said before that Kubernetes wasn't really designed for use with trusted CAs as the cluster issuers, but if people want to do it for some reason, and are willing to pay for it, the I guess we'll do our best to help.

With regards to the SAN thing, that is only for server certificates. If you can find something saying otherwise that'd be great, but as far as I know that policy was specifically pushed by the CA/Browser forum for server certificates only.

**Comment by tsde** [comment]
Hi,

> RKE2 does not set this by default, so we're probably fine, but it is something end users should be aware of

When deploying a cluster with RKE2 (version `v1.24.9+rke2r1`), the API server is started with the `--requestheader-allowed-names`. In my case, it is set to `--requestheader-allowed-names=system:auth-proxy`. I don't know if RKE2 is directly setting it, but it is there nonetheless and without having it specified in RKE2 config.

Regarding, the CN field deprecation, it's been published since May 2000 (damn, I'm getting old :smile: ) : https://datatracker.ietf.org/doc/html/rfc2818#section-3.1. The relevant bit being

> Although the use of the Common Name is existing practice, it is deprecated and Certification Authorities are encouraged to use the dNSName instead.

Still, many continue to rely on this field instead of the SAN field. Chances are that this field will never be removed from the spec ^^

**Comment by brandond** [comment]
RFCs aside, I am not aware of any packages that use the SAN field for client cert auth. Pretty much everything I've ever seen uses the cert subject as the source of identity information when using client certs for authn/authz.
