### ISSUE TITLE
Bump Harvester Cloud Provider & CSI-driver chart

### ISSUE THREAD

**Issue by guangbochen** [rancher/rke2#3765]
The latest version of Harvester Cloud Provider and Harvester CSI Driver contains a couple of bug fixes needed for Harvester 1.1.2.
- harvester-cloud-provider: 0.1.5, chart-version: v0.1.14
- harvester-csi-driver: 0.1.4, chart-version: v0.1.15

We also want to backport this to RKE2 v1.22.x, v1.23.x, v1.24.x., v1.25.x

**Comment by irishgordo** [comment]
_First Validation Attempt:_ **failed**

When attempting to validate with:
- Harvester Version: master-14bbee2c-head 
- Harvester Version: v1.1.1

And Rancher version v2.7.0.
With the metadata config set to:
https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/january_2023_rke2/data/data.json

We noticed that we are unable to select Harvester as a cloud provider.
Or proceed further with building an RKE2 Cluster.

Screenshots:
![Screenshot from 2023-01-19 14-42-58](https://user-images.githubusercontent.com/5370752/213771651-37e9f9c9-0e53-408a-b35f-07a2d21ee535.png)
![Screenshot from 2023-01-19 14-41-58](https://user-images.githubusercontent.com/5370752/213771654-6ce98aa2-1cf4-4220-a67c-73d8b38cbbfe.png)
![Screenshot from 2023-01-19 14-35-34](https://user-images.githubusercontent.com/5370752/213771656-6af9f34c-5c6a-4b44-9514-75ec99eae0b3.png)
![Screenshot from 2023-01-19 14-29-51](https://user-images.githubusercontent.com/5370752/213771658-49a8eb86-ac05-42e8-bc6d-e202d71e51b1.png)


cc: @noahgildersleeve

**Comment by brandond** [comment]
[irishgordo](https://github.com/irishgordo) this sounds like a Rancher or Dashboard issue, or perhaps a problem with the chart data in the `kontainer-driver-metadata` branch you're using? RKE2 itself does not determine the cluster drivers available for use by Rancher.

**Comment by mantis-toboggan-md** [comment]
I'm not super familiar with this particular area, but I looked through the dashboard code for that dropdown and it appears that the Harvester provider option is disabled if the currently-selected rke2 `harvester-cloud-provider` or `harvester-csi-provider` chart versions are not within the ranges specified in the setting (`harvesterhci.io.setting`) `harvester-csi-ccm-versions`. If I'm reading [this](https://github.com/harvester/harvester/blob/v1.1/pkg/settings/settings.go#L52) right (big if tbh) the default value for that setting in 1.1.1 would exclude these bumped chart versions...does that help at all @irishgordo ?

**Comment by brandond** [comment]
```golang
HarvesterCSICCMVersion = NewSetting(HarvesterCSICCMSettingName, `{"harvester-cloud-provider":">=0.0.1 <0.1.14","harvester-csi-provider":">=0.0.1 <0.1.15"}`)
```

That looks correct, but is going to be problematic as the rke2-charts build process adds a two-digit package version to the end of the upstream chart version. The `<0.1.14` constraint is going to fail, as the RKE2 chart version is `0.1.1400` or  `<0.1.1401` and so on. 

This behavior comes from https://github.com/rancher/charts-build-scripts. We could try upgrading the charts scripts, but the new scheme will be worse, as it will switch to the rancher-charts style `100.0.0+up0.1.14` version format - see https://github.com/rancher/charts/tree/dev-v2.7/charts/harvester-cloud-provider/101.0.0%2Bup0.1.13

This change to lock the chart versions seems to have been made here: 
* https://github.com/harvester/harvester/pull/2812

I don't think this is going to be usable due to how both RKE2 and Rancher repackage the harvester charts.

**Comment by brandond** [comment]
I guess a quick fix would be to just lie to KDM and say that the RKE2 chart is coming from the harvester chart repo with version `0.1.14`. I think we have CI checks that would prevent us from doing this? It's worth trying I guess.

cc @briandowns

**Comment by brandond** [comment]
hmm I'm looking at Rancher and it seems like perhaps it doesn't ship with a chart repo for harvester, so I guess that won't work after all.
https://github.com/rancher/rancher/blob/release/v2.7/pkg/data/dashboard/repo.go#L42-L53
