### ISSUE TITLE
Failure to reencrypt concurrently modified secret during secrets encryption

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke2#3801]
**Environmental Info:**
RKE2 Version: v1.25.5+rke2r2

Cluster Configuration:

1 server (rancher provisioned, but should be reproducible standalone)

**Describe the bug:**

Ocassionally, `rke2 secrets-encrypt reencrypt` will fail to update a secret as it may be updated outside of rke2, which cause secrets encryption to fail.

**Steps To Reproduce:**

- Installed RKE2: Rancher provisioned
- Complete the expects steps for the prepare and rotate stages (`rke2 secrets encrypt prepare`, `systemctl restart rke2-server`, `rke2 secrets-encrypt rotate`, `systemctl restart rke2-server`)
- Run the `rke2 secrets-encrypt reencrypt` command

**Expected behavior:**

`rke2 secrets-encrypt reencrypt` completes successfully.

**Actual behavior:**

The following error is recorded: `Failed to reencrypted secret: Operation cannot be fulfilled on secrets "serving-cert": the object has been modified; please apply your changes to the latest version and try again`.

**Additional context / logs:**

The secret in question is the dynamiclistener `serving-cert`, which is likely being updated asynchronously.

I've diagnosed the issue as coming from here: https://github.com/k3s-io/k3s/blob/1c17f05b8ee669ad309ad344dc443b0ae919328a/pkg/secretsencrypt/controller.go#L224-L228

I plan to test a potential fix, but need time to set up a reliably reproducible environment due to the raciness of this issue, I've only seen this issue twice out of ~ 25 attempts.

**Comment by brandond** [comment]
cc @dereknola

**Comment by brandond** [comment]
This should probably be opened against k3s and not RKE2, since the rotation logic all lives in k3s. 

It should be pretty easy to wrap the update at https://github.com/k3s-io/k3s/blob/master/pkg/secretsencrypt/controller.go#L226in a retry - we do this pretty much everywhere else that we are updating objects for example at https://github.com/k3s-io/k3s/blob/master/pkg/secretsencrypt/controller.go#L95

**Comment by dereknola** [comment]
Yeah I talked to Jake about this. Should be fairly straightforward.

**Comment by VestigeJ** [comment]
##Environment Details
VERSION=v1.26.1+rke2r1

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*
```
Linux 5.4.0-1041-aws x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.2 LTS"
```

*Cluster Configuration:*
From Rancher provisioned node

$ sudo cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml //intentionally falsified
```
{
  "advertise-address": "13.32.32.32",
  "agent-token": "SOLARRECTENNAENERGYGENERATION",
  "cni": "multus,cilium",
  "disable-kube-proxy": false,
  "etcd-expose-metrics": false,
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-external-ip": [
    "13.32.32.32"
  ],
  "node-ip": [
    "13.32.32.32"
  ],
  "node-label": [
    "rke.cattle.io/machine=8463d715-6dc3-4789-9c9d-8784bc152b31"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "tls-san": [
    "13.32.32.32"
  ],
  "token": "LEGENDARYLETTUCELOTUSWRAPS"
}
```


<details>
<summmary><h4> VERSION=v1.23.16+rke2r1  </h4></summary>



Provisioned single node install via rancher v2.7.2-rc5

```
$ sudo rke2 secrets-encrypt
$ sudo rke2 secrets-encrypt enable
$ sudo rke2 secrets-encrypt prepare
$ sudo systemctl restart rke2-server
$ sudo rke2 secrets-encrypt rotate
$ sudo systemctl restart rke2-server
$ sudo rke2 secrets-encrypt reencrypt
$ rke2 -v
```

**Results:**

$ sudo rke2 secrets-encrypt enable
```
secrets-encryption enabled
```

$ sudo rke2 secrets-encrypt prepare
```
prepare completed successfully
```

$ sudo systemctl restart rke2-server
//no output service restarted normally

$ sudo rke2 secrets-encrypt rotate
```
rotate completed successfully
```

$ sudo systemctl restart rke2-server
//no output service restarted normally

$ sudo rke2 secrets-encrypt reencrypt
```
reencryption started
```

$ rke2 -v
```
rke2 version v1.26.1+rke2r1 (0ab4614b13daa5a49e484249a49012918d46ed22)
go version go1.19.5 X:boringcrypto
```

</details>


ATTENTION TO Jake's message for frequency: "I plan to test a potential fix, but need time to set up a reliably reproducible environment due to the raciness of this issue, I've only seen this issue twice out of ~ 25 attempts."

**Comment by VestigeJ** [comment]
Closing this branch check - the test has passed on the previous three branches and this version is not yet relevant for Rancher.
