### ISSUE TITLE
When running in CIS mode, we need to change what we do around protect-kernel-defaults

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#389]
When running with the CIS profile turned on, we have logic that ensures the following kernel parameters are set as defined:
```
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.keys.root_maxbytes=25000000
kernel.panic=10
kernel.panic_on_oops=1
```
rke2 will not modify these, it will just error out if their values aren't set as expected.

This was done to conform with CIS control 4.2.6, but that is not what the control is looking for. The control just requires that that the kubelet flag `protect-kernel-defaults` is set to true. Setting this flag to true will cause the kubelet to error out if the parameters are not set to the above values (see this pr where the feature was introduced: https://github.com/kubernetes/kubernetes/pull/27874/files)

Also, the rke2 code is checking 5 kernel parameters, but only four are required by the kubelet (see: https://github.com/kubernetes/kubernetes/blob/587b1f845a445e83a2288545f59cb22bf211cf52/pkg/kubelet/cm/container_manager_linux.go#L247-L253). `kernel.keys.root_maxbytes=25000000` is not needed.

So here's the behavior we need:
1. When running with `profile=cis-1.5`, let's keep our check for the kernel params as a convenience for the user so that they don't have to dig through kubelet logs. But DROP the check for `kernel.keys.root_maxbytes=25000000`.
2. When running with `profile=cis-1.5`, set the kubelet flag `protect-kernel-defaults` to true. NOTE: we expose this flag direclty in `rke2 agent` for the user to set. If the user has explicitly set it to false and supplied `profile=cis-1.5`, we should error out. If they have not explicitly set it, then we should just set it to true for them. ...This is just my initial thought on the behavior. open to alternatives.

**Comment by rancher-max** [comment]
#### Validated on beta23

- When running with profile=cis-1.5, let's keep our check for the kernel params as a convenience for the user so that they don't have to dig through kubelet logs. But DROP the check for kernel.keys.root_maxbytes=25000000 -- This is working. If I don't have this value, rke2 still installs successfully, but if I don't have one of the other values, it fails to continue install giving errors like: `level=fatal msg="invalid kernel parameter value kernel.panic=-1 - expected 10\n"`
- When running with profile=cis-1.5, set the kubelet flag protect-kernel-defaults to true. -- This is working. When CIS mode is not set, this parameter is not set on the kubelet at all.
- rke2 fails to start server node and fails to join agent node in cis mode when setting `protect-kernel-defaults` to false explicitly: `level=fatal msg="--protect-kernel-defaults must be true when using --profile=cis-1.5"`
- Setting everything correctly enables CIS mode correctly
