### ISSUE TITLE
hide rke2-uninstall.sh to avoid accidental deletion of RKE2

### ISSUE THREAD

**Issue by harridu** [rancher/rke2#3928]
Its easy to run rke2-uninstall.sh instead of rke2-killall.sh by accident or out of confusion, esp. if command line completion is enabled. This is fatal. I would suggest to better hide the uninstall scripts.

**Comment by brandond** [comment]
I don't believe this is something we're likely to do. There are a lot of mistakes an inattentive cli user may make; every user who's ever run `rm -rf /` on accident can sympathize. The solution is to type carefully, rather than expecting your tools to remove every potentially harmful command from being suggested by shell completion.

**Comment by harridu** [comment]
Of course its a mistake to run the harmful command. Moving it to somewhere else (outside of the usual $PATH) would be a defensive measure not hurting anybody.

It is even lacking a confirmation dialog, nor does it catch something like "rke2-uninstall.sh --help". Not best practice.

**Comment by harridu** [comment]
I highly appreciate your work on RKE2.

**Comment by caroline-suse-rancher** [comment]
Closing this as it's not currently in our plans to modify
