### ISSUE TITLE
Add support for PodSelector in DrainSpec for SUC Upgrades

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#4021]
**Description:**
Currently there is no PodSelector support in the Drain Spec of the system-upgrade-controller chart. We should add support for that so that we can specify which pods should be drained as an opt-in. 

**Testing Considerations:**
1. Setting the arg to be one specific pod that is part of a Deployment, such as `app.kubernetes.io/name=testpod1` and ensure only that pod gets drained from the node.
2. Setting the arg to be a batch of pods that are part of multiple workloads (including both Deployments and Daemonsets), such as `app.kubernetes.io/type=testbatch1` and ensure only those pods get drained from the node. The Daemonsets should come back before the node is uncordoned, but the deployments should not.
3. Not setting the arg at all.
4. Setting multiple selectors to ensure it can delete a comma separated list, such as `app.kubernetes.io/name=testpod1,app.kubernetes.io/name=testpod2`

**Comment by aganesh-suse** [comment]
OS: Ubuntu 22.04
Setup: 1 server/ 1 agent.
Upgrades tested: v1.25.9-rc1+rke2r1 to (v1.26.1+rke2r1 through v1.26.4+rke2r1)
 
https://github.com/rancher/system-upgrade-controller/pull/239
^^ this fixes the issue found that "matchExpressions" was not being evaluated correctly.

Retested with the above fix as follows:  

Use: kubectl
apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.11.0-dev.3/system-upgrade-controller.yaml

Created multiple pods, services, daemonsets using labels. 

Using the "podSelector" - verified that we could use "matchLabels" and/or "matchExpressions" to match the pods that we want drained. Verified that those that did not match - don't get drained. 

Also verified other error messages as follows: 
```
Verified:
     message: spec.drain cannot specify both deleteEmptydirData and deleteLocalData
     reason: Error
     status: "False"
     type: Validated
```
Verified format checking errors: 
```
Message:           values[0][app]: Invalid value: "clusterip-demo, clus-1": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

Sample:
```
 podSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values: 
            - clusterip1
      matchLabels:
        app1: clusterip-demo
```
generated a drain container with args as: 
```
drain
     ip-172-31-34-69
     --pod-selector
     app.kubernetes.io/name in (clusterip1),app1=clusterip-demo,!upgrade.cattle.io/controller
     --ignore-daemonsets
     --delete-emptydir-data
     --force
```

If we give several matchLabels and matchExpressions, AND operation happened and the subset of matched pods were terminated. Since this is a "key/value" pair - the "keys" need to be unique, and hence have only one string value.
 
As noticed, by default "--ignore-daemonsets" get set. 

Verified "Plans" generated had been "Validated" - and correct error messages were propagated. 
Verified the "Jobs" and the "pods" generated for the system-upgrade namespace, did not have any unexpected errors. 

Noticed this a few times: 
```
Warning  FailedMount  7m     kubelet            MountVolume.SetUp failed for volume "kube-api-access-xprzx" : object "system-upgrade"/"kube-root-ca.crt" not registered 
```
Apparently, it is normal to see if you try to create a pod at the exact same time as the namespace. the kube-root-ca configmap doesn’t get created immediately.

Also, 
The kubelet version downloaded was rancher/kubectl:v1.21.9 and not rancher/kubectl:v1.21.14 (per the code change above). But this should be fine as well per Brad. 

Overall, this looks good.

**Comment by aganesh-suse** [comment]
Tested by matching a daemonset pod label and providing "ignoreDaemonSets: false" value in the plan.yaml. 
The drain container logs with the error message: 
```
kup logs pod/apply-rke2-agent-on-ip-172-31-34-69-with-778736eaceef4248-f5lfb -c drain
node/ip-172-31-34-69 already cordoned
error: unable to drain node "ip-172-31-34-69", aborting command...

There are pending nodes to be drained:
 ip-172-31-34-69
error: cannot delete DaemonSet-managed Pods (use --ignore-daemonsets to ignore): default/othertest-deploy-4czsr
```

Everything looks good.

**Comment by aganesh-suse** [comment]
Matched pods of a Deployment getting evicted: 
```
kup logs pod/apply-rke2-agent-on-ip-172-31-34-69-with-224d5e8d1760a055-k7hcn drain
node/ip-172-31-34-69 cordoned
evicting pod default/nginx-nodeport-deployment-5b595d4966-jk2xk
evicting pod default/nginx-nodeport-deployment-5b595d4966-g6rkp
pod/nginx-nodeport-deployment-5b595d4966-jk2xk evicted
pod/nginx-nodeport-deployment-5b595d4966-g6rkp evicted
node/ip-172-31-34-69 evicted
```

**Comment by aganesh-suse** [comment]
Verified that if we do not provide any "drain" section in the plan.yaml - a corresponding drain container is not created by the plans/jobs/pods of system-upgrade controller.
```
kup logs pod/apply-rke2-agent-on-ip-172-31-43-233-with-4d0210b5aba73fd-8blbh
Defaulted container "upgrade" out of: upgrade, prepare (init)
``` 
```
kup logs pod/apply-rke2-agent-on-ip-172-31-43-233-with-4d0210b5aba73fd-8blbh drain
error: container drain is not valid for pod apply-rke2-agent-on-ip-172-31-43-233-with-4d0210b5aba73fd-8blbh
```
