### ISSUE TITLE
Bump harvester csi driver to v0.1.16

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#4038]
Proposed Changes
Bump harvester csi driver version

Types of Changes
Version bump

Verification
Deploy RKE2 with Harvester; note chart versions

Linked Issues
https://github.com/harvester/harvester/issues/3571

Linked PR
#3999 

Further Comments

**Comment by VestigeJ** [comment]
Waiting for harvester team to validate...

**Comment by TachunLin** [comment]
#### Test scope 
|                   | v1.26.3-rc1 | v1.25.8-rc1 | v1.24.12-rc1 |
|-------------------|:-----------:|:-----------:|:------------:|
| Rancher v2.7-head |             |             |              |
| Rancher v2.7-head |             |             |              |

#### Test scenarios
1. RKE2 guest cluster can include csi-driver `v0.1.6` chart installation
2. In guest cluster, default storage class set to Harvester 
3. Can create PVC with Harvester storage class
4. Can attach PV to deployment 
5. The created PV on Rancher can display on Harvester volume page

**Comment by TachunLin** [comment]
We found on Rancher `v2.6-head` and `v2.6.11`, when we upgrade the K8s version of RKE2 guest cluster from `v1.24.10` to `v1.25.8-rc1` directly.

* After upgrade, the csi-driver application version **did not** change to `v0.1.16` accordingly
![image](https://user-images.githubusercontent.com/29251855/226846371-192ef038-c0de-4fa6-832e-c1e7421df057.png)

* Check the yaml content, the app version and helm chart did not update too
![image](https://user-images.githubusercontent.com/29251855/226846591-bd55e6de-68e9-4f65-894e-8deceb768377.png)

* But when we check the csi-driver daemonset, the helm chart already update to 0.1.16
![image](https://user-images.githubusercontent.com/29251855/226846788-c87e4d2f-4179-41c9-9468-7a00184028ca.png)

* And the csi-driver pod image version also update to 0.1.15
![image](https://user-images.githubusercontent.com/29251855/226846914-dd68dce4-a449-4d82-a52b-7c211e9de57d.png)

**Comment by TachunLin** [comment]
In comparison, on Rancher `v2.7-head` , when we upgrade the K8s version of RKE2 guest cluster from v1.25.7 to v1.25.8-rc1 directly.

* The csi-driver application version can change to v0.1.16 accordingly
![image](https://user-images.githubusercontent.com/29251855/226858628-340e305c-d509-43c4-928d-783c08c3a465.png)

* The csi-driver daemonset, the helm chart already update to 0.1.16
![image](https://user-images.githubusercontent.com/29251855/226859029-b9c98b84-deb2-4913-b907-b5b207a93c8e.png)

* The csi-driver pod image version also update to 0.1.15
![image](https://user-images.githubusercontent.com/29251855/226859222-325c2142-791b-4b62-94b0-4b3f80dd1c81.png)

**Comment by rancher-max** [comment]
Ah this should be because Rancher v2.6.x does not support k8s v1.25.x, so this shouldn't block anything! It looks like all other scenarios passed, so we should be okay to close this. Thank you so much for your thorough testing and help on this!! I'll let you click the close button if you agree this is fine 👍

**Comment by TachunLin** [comment]
@brandond , @rancher-max 
Thanks for your instruction and information. I agree we can close it since for Rancher v2.6.x does not support k8s v1.25.x.   
Thus we could focus on the k8s v1.24.x part.  

Beside I also double confirm if we upgrade k8s version from `v1.24.10` to `v1.24.12-rc1` 
And after that, we can continue upgrade to `v1.25.8-rc1` even further to `v1.26.3-rc1` and keep the csi-driver version updated to the desired `0.1.16` 

![image](https://user-images.githubusercontent.com/29251855/227094758-8f497d6f-af4f-4c23-bf93-631affe5a1c4.png)

![image](https://user-images.githubusercontent.com/29251855/227094857-bcae7a02-9205-4241-bea1-01179b5f366b.png)

Thus, for Rancher v2.6.x user, the suggested k8s upgrade path to leverage latest csi-driver would be 
`v1.24.10 -> v1.24.12-rc1` -> `v1.25.8-rc1` -> `v1.26.3-rc1`
