### ISSUE TITLE
[release-1.25] Bump harvester csi driver to v0.1.16

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#4039]
Backport for #4038 

PR: #4004

**Comment by VestigeJ** [comment]
Waiting for harvester team to validate...

**Comment by TachunLin** [comment]
Verified **failed** on Rancher `v2.6-head` and `v2.6.11` with Harvester `v1.1.2-rc3`. Close this issue.

### Result
After update Kubernetes version of the RKE2 guest cluster from `v1.24.10` to `v1.25.8-rc1`
The csi-driver application version did not upgrade to `v0.1.16` accordingly

![image](https://user-images.githubusercontent.com/29251855/226846371-192ef038-c0de-4fa6-832e-c1e7421df057.png)

Please refer to the details in https://github.com/rancher/rke2/issues/4038#issuecomment-1479209014


### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: v1.1.2-rc3
* Rancher version: `v2.6.11` , `v2.6-head` (a2423b1) 
* K8s version: `v1.25.8-rc1`
* csi-driver version: 0.1.16

### Verify Steps
1. In Harvester setting, set the version number from `v1.1.2-rc3` to `v1.1.2` (for Rancher v2.6-head)
2. Import Harvester to Rancher 
3. Provision the RKE2 cluster with K8s version v1.24.10
4. Check the csi-driver version on guest cluster application page
5. Update the YAML of the guest cluster 
6. Change the kubernetes version to `v1.25.8-rc1+rke2r1`
7. Wait the update complete
8. Check the csi-driver version on guest cluster application page



https://github.com/rancher/rke2/issues/4038#issuecomment-1479209014

**Comment by brandond** [comment]
This sounds like an issue with either Rancher or KDM, not rke2. Can you check the actual chart and pods in the downstream cluster? I believe they are being upgraded. Rancher however is not showing the correct versions.

**Comment by TachunLin** [comment]
According to the comment of https://github.com/rancher/rke2/issues/4038#issuecomment-1479718696

Since Rancher v2.6.x does not support k8s v1.25.x. I think we can focus only on the k8s v1.24.x part.   

Beside I also double confirm if we upgrade k8s version from v1.24.10 to v1.24.12-rc1
And after that, we can continue upgrade to v1.25.8-rc1 even further to v1.26.3-rc1 and keep the csi-driver version updated to the desired 0.1.16

![image](https://user-images.githubusercontent.com/29251855/227094758-8f497d6f-af4f-4c23-bf93-631affe5a1c4.png)

![image](https://user-images.githubusercontent.com/29251855/227094857-bcae7a02-9205-4241-bea1-01179b5f366b.png)

Thus, for Rancher v2.6.x user, the suggested k8s upgrade path to leverage latest csi-driver would be 
`v1.24.10 -> v1.24.12-rc1` -> `v1.25.8-rc1` -> `v1.26.3-rc1`


On Rancher v2.7-head, we also passed all test scenario of k8s `v1.25.x`
Thus we can close this issue.
