### ISSUE TITLE
Rancher rke2:v1.27.1-rke2r1 in HA mode One of the control plane nodes get stuck during service restart

### ISSUE THREAD

**Issue by ashish1993** [rancher/rke2#4291]
**Environmental Info:**
RKE2 Version: 1.27.1-rke2r1 

Node(s) CPU architecture, OS, and Version: 

CPU: 16GB
OS: Ubuntu 20.04
Ram: 32GB
300 Gb HDD Disk

Cluster Configuration:
3 control plane nodes as master
2 as worker

**Describe the bug:**
After configuring keycloak in all 3 cp nodes . One of the cp gets stuck with rke2-server service stuck in activating state.
The api server shows: **invalid bearer token, service account token has been invalidated**

**Steps To Reproduce:**

- Installed RKE2: 
- Deploy keycloak and update keycloak configuration across all 3 CP
-
![image](https://github.com/rancher/rke2/assets/5062236/2739b645-1772-4712-9c96-e429a5a0219c)

- restart all 3 cp one by one with a wait of 1 min

**Expected behavior:**

All the 3 cp shuld be up
**Actual behavior:**

one of the  CP gets stuck in activating state
**Node restart seems to fix the issue and the rke2-server.service comes back up**
**Additional context / logs:**

[rke2.tar.gz](https://github.com/rancher/rke2/files/11563625/rke2.tar.gz)

**Comment by brandond** [comment]
All you've attached is the pod logs; please also attach the rke2-server journald logs for the affected node, along with the log from `/var/lib/rancher/rke2/agent/log/kubelet.log`

**Comment by brandond** [comment]
I will note that I'm not really sure what to expect when changing the OIDC issuer configuration on a running cluster; this isn't something I've ever tested, and in general I would advise having this configured during initial cluster startup. I suspect that adding it later may invalidate existing service account tokens, which would require restarting pods that use service accounts, in order to get new tokens.

**Comment by ashish1993** [comment]
@brandond Thanks for quick response.
The keycloak is part of the cluster so cant put it to initial cluster config.
PFA updated logs
[allrke2.zip](https://github.com/rancher/rke2/files/11572552/allrke2.zip)

**Comment by brandond** [comment]
Hmm, that's not a pattern I've seen before. Will the apiserver come up from a cold shutdown, where the in-cluster oidc endpoints for keycloak are not available because no pods are running yet?

**Comment by brandond** [comment]
It looks like the kubelet can't start the static pods, because the webhook isn't available. This prevents the node from coming up, because etcd and the apiserver itself are hosted in static pods:
```
E0526 07:13:59.536517    3578 webhook.go:154] Failed to make webhook authenticator request: Post "https://127.0.0.1:6443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 127.0.0.1:6443: connect: connection refused
E0526 07:13:59.536584    3578 server.go:309] "Unable to authenticate the request due to an error" err="Post \"https://127.0.0.1:6443/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp 127.0.0.1:6443: connect: connection refused"
E0526 07:14:01.890275    3578 kubelet.go:1875] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[file1 file2 file3 file4 file5 file6 dir0 file0], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition" pod="kube-system/etcd-bmo-cp-1"
```

I'm not sure that it will work to have the issuer running within the cluster; you appear to be highly likely to get stuck in a deadlock like this where the cluster cannot start, because critical functionality necessary for the cluster to operate, is hosted within the cluster itself.

**Comment by brandond** [comment]
No, not on our side. Upstream has been tweaking some stuff with regards to how pods are sync'd within the kubelet, but that's all pretty low-level and its hard to know what impact something like that would have on what you're trying to do here. All I see is that the kubelet is stuck trying to validate tokens, but can't because the cluster isn't up yet.

**Comment by ashish1993** [comment]
update: 1.27.2 seems to work.  anything added in that?

**Comment by brandond** [comment]
No, I can't think of anything specific that we changed.

**Comment by caroline-suse-rancher** [comment]
Closing since the issue seems to be resolved - please open a new issue if the problem reoccurs
