### ISSUE TITLE
Uninstall script fails when `/var/lib/kubelet` is a mount point

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#4475]
*from @aceeric in https://github.com/rancher/rke2/pull/4470*

In some cases a machine is configured with /var/lib/kubelet as a mount rather than a directory and this causes the rke2-uninstall.sh script to fail where it is removing directories so the machine isn't fully cleaned up. If you use the Rancher Federal Ansible RKE2 installer to install/re-instal RKE2, the presence of the files causes a re-install to fail.

**Comment by ShylajaDevadiga** [comment]
### Validated on master branch using commit id 77934df71e4bb7b750d4b682ddcd3d0d170281ca
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```

*Cluster Configuration:*
Single node

*Config.yaml:*
```
cat /etc/rancher/k3s/config,yaml
write-kubeconfig-mode: "0644"
```
 ## Validation steps
1. Create an instance with two drives and configure /var/lib/kubelet as a mountpoint for second drive
2. Copy config.yaml
3. Install rke2
4. Verify /var/lib/kubelet is mounted and used
5. Uninstall rke2
6. Verify content of /var/lib/kubelet is deleted and proceeds with uninstall scripts cleaning up  /var/lib/rancher

**Validation results:**
```
$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
...
nvme0n1      259:0    0    30G  0 disk 
├─nvme0n1p1  259:1    0  29.9G  0 part /
├─nvme0n1p14 259:2    0     4M  0 part 
└─nvme0n1p15 259:3    0   106M  0 part /boot/efi
nvme1n1      259:4    0    30G  0 disk /var/lib/kubelet
```
```
$ ls /var/lib/kubelet/
cpu_manager_state  device-plugins  lost+found  memory_manager_state  plugins  plugins_registry  pod-resources  pods  volumeplugins
$ ls /var/lib/rancher/
rke2
```
Device busy error message is seen as expected due to /var/lib/kubelet being a mount point.
Uninstall process continues with next steps
```
sudo rke2-uninstall.sh
...
+ rm -rf /var/lib/kubelet
rm: cannot remove '/var/lib/kubelet': Device or resource busy
+ true
+ rm -rf /var/lib/rancher/rke2
+ rm -d /var/lib/rancher

```
Content is deleted
```
$ ls /var/lib/kubelet/

$ ls /var/lib/rancher
ls: cannot access '/var/lib/rancher': No such file or directory
```
