### ISSUE TITLE
Support for etcd snapshot and restore

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#45]
Add support for RKE2 snapshot, backup, and restore ~via Rancher~ via CLI.
+ must also take automatic snapshots periodically.
+ On by default
+ Controlled via config args
+ ~Supports S3 (need this capability similar to RKE1)~ Not need for 1.0
+ Restore functionality folded into rke2 `--cluster-reset` - You restore by triggering a cluster-reset with a restore path arg specifified

**Comment by rancher-max** [comment]
**Using rke2 `beta16` to validate:**

- Overall the flags are working well
- Cluster backups from local work as expected
  - Note that when doing local backups, if the node(s) that were specified to contain a local backup are deleted, then those backups are also lost.
- Must install from binary instead of install script if wanting the ability to use backups: https://github.com/rancher/rke2/issues/293
- Not working in k3s for some reason: https://github.com/rancher/k3s/issues/2201

**Comment by rancher-max** [comment]
- This has now been fully validated in k3s
- Going to do another round of validations in rke2, especially regarding quorum loss scenario, and then can close assuming that works as expected.
- One minor issue regarding logging opened: https://github.com/rancher/k3s/issues/2244

**Comment by rancher-max** [comment]
I think the support for etcd snapshot and restore is functional. There are a few issues that came from testing this that should be addressed on their own at this point. 
Namely https://github.com/rancher/rke2/issues/320 and https://github.com/rancher/rke2/issues/353
