### ISSUE TITLE
Feature/Question Consolidated etcd

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rke2#453]
This is a combined question and feature request. I started taking away the management of etcd from RKE just a month ago due to massive problems with multi network connectivity and a goal I wanted to discuss earlier already but always forgot.

So what I am doing already now is to consolidate etcd and let multiple clusters run off etcd to improve maintainability of the same and resource utilization. So exactly this is also the question here: Why was the design decision made to have strictly separated etcd servers per k8s cluster and not being able to maintain etcd consolidated as an option?

My solution works of course, but I have the situation similarly for a lot of customers in their in house setups, which would basically want this in some stage. If rancher + rke could handle consolidating etcd servers would make this a no brainer.

I hope I still hit early enough in development of rke2 to consider this.

**Comment by cjellick** [comment]
@ibuildthecloud recently told me he wants to bring K3s's KINE feature to RKE2 and basically run it as a static pod. If we did this,  that would bring the "external datastore" functionality of k3s to RKE2. That would allow you to connect to an externally managed etcd.

**Comment by wzrdtales** [comment]
I was more hoping of rancher/rke being able to maintain the centrally managed etcds (I don't consider a single huuuuuuge one, but many big). But that is maybe too much to ask, but it would just be so perfectly clean and integrated with the solution that takes care of all the stuff around kubernetes already.

**Comment by amdonov** [comment]
We're very interested in kine and the use of an external relational database with rke2. Should I open a different ticket for that feature request?

We find it much easier to upgrade/replace server instances if we're not concerned with maintaining a quorum. It's also nice that with k3s and an external database, all server instances can be created the same way rather than the first server having a different configuration than others that join it.
