### ISSUE TITLE
When using additional runtimes, fatal error of "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#4984]
RKE2 Tracking for https://github.com/k3s-io/k3s/issues/8754
**Is your feature request related to a problem? Please describe.**

**Comment by gusmann** [comment]
Just started to run into this a few days ago as our upgrade controller picked up on the stable channel update for v1.26.10-rke2r1. manually pushed a containerd.toml.tmpl with the right config for now.

**Comment by VestigeJ** [comment]
@gusmann We're doing tests now if you have workloads to test against - feel free to take a node and use this commit_id. Not to be used in production 😉 

```
INSTALL_RKE2_COMMIT=d202650430a0f2ee5e51915dbe3ef141e849768b
```

**Comment by gusmann** [comment]
I think we'll have to wait until a new `rke2-upgrade` [image](https://hub.docker.com/r/rancher/rke2-upgrade/tags) is built/pushed since the [upgrade controller](https://github.com/rancher/system-upgrade-controller/) uses that image to execute the upgrade. Tried setting `version` to the commit just to see what would happen and the controller wrote that as the image tag. And yea, this is a dev cluster so no big deal.
![image](https://github.com/rancher/rke2/assets/10593140/ca68ad71-c710-4fb7-9b06-be6a84aaca5d)

**Comment by brandond** [comment]
commit IDs can only be used with the rke2 install script; for rancher or system-upgrade-controller you'll have to wait for a full release.

**Comment by VestigeJ** [comment]
Still testing this across 1.27, 1.26, 1.25 
https://github.com/rancher/rke2/commit/981fc32b589e0a803c5f5f85be9f696a46fe1e8c
https://github.com/rancher/rke2/commit/c410d325dc6ce941129dc347368d5b40c7e15312
https://github.com/rancher/rke2/commit/006d12c834b6294ec15a21319b91893b27d8f008
