### ISSUE TITLE
Default node label for role worker is missing for agent

### ISSUE THREAD

**Issue by curantes** [rancher/rke2#505]
after setup of a cluster with 3 master nodes with roles etcd,master (rke2-server)r and 3 worker nodes (rke2-agent) and run a `kubectl get nodes` the worker nodes have role <none>.

I had to add below to agent config
```
node-label: ["node-role.kubernetes.io/worker=true"]
```
This is something I think sould be set as default since all agents are workers and does not run controlplane (with etcd)

This would be a better out-of-box experience.

**Comment by cjellick** [comment]
Was just having a related conversation about this. The worker role (really all node roles) are just arbitrary strings that have no impact by default in vanilla k8s. For example, the existence of that label doesn't impact scheduling in anyway.

Can you help me understand what are you seeking to accomplish with having the worker role?

One thing that we likely need to do is **taint** server (aka "master" or "controlplane") nodes by default so that workloads dont land there by default.

**Comment by curantes** [comment]
The taint issue was actually another thing I was to bring up so thanks for creating #509 

This issue is about what for example kubectl is reporting about node roles when issuing `kubectl get nodes` Default now after bootstraping a rke2 cluster is that controlplane a.k.a master nodes have the roles **etcd,master**  but the worker nodes does not have any roles according to kubectl output.

I know this will not impact on functionality but most kubernetes distributions (kubeadm and rke1) set this to **worker**  by default.

**Comment by cjellick** [comment]
Thanks. Good points.

I poked around at a few cloud-provided k8s to see what they do and this is what I found:
- EKS - none
- GKE - none
- AKS - "agent"

Like you said, rke1 and kubeadm both explicitly label workers. 

So, there's an obvious lack of consistency. Will ponder further.
