### ISSUE TITLE
LoadBalancer service got stuck with message: Service is ready:Load balancer is being provisioned

### ISSUE THREAD

**Issue by serhiynovos** [rancher/rke2#5143]
I installed Harvester 1.2.1 and connected Rancher 2.8.0 and then created RKE2 cluster with Cilium CNI.

I created IP pool with a few available IP addresses and Virtual Machine load balancer is working fine. Then I deployed a service which has LoadBalancer service and it got stuck with the next message "Service is ready:Load balancer is being provisioned"

On Harvester side I see LB for this service is created and active but it does not show which IP address is used (but in IP pool I see one more IP address was occupied)

**Comment by brandond** [comment]
I don't believe this is the correct place for your issue. Please reopen this issue against harvester, as you are using the harvester load-balancer controller.

**Comment by pck** [comment]
I had a similar problem, and switching from Cilium to Calico CNI didn't help.
Rancher provisioned RKE2 with `3 * "etcd + control" + 2 * worker` nodes and the kube-system/kube-vip daemonset was not running anywhere. (I think because of a NoExecute-taint on nodes with etcd?) Reconfiguring the cluster to `3 * etc + 2 * control + 2 * worker` solved my issue.

**Comment by serhiynovos** [comment]
@pck
Please refer to this issue https://github.com/harvester/harvester/issues/4891

 The issue that kube-vip DeamonSet did have toleration to run on etcd nodes only control plane. This comment solves the problem https://github.com/harvester/harvester/issues/4891#issuecomment-1866091155
