### ISSUE TITLE
Upgrade k8s cluster steps

### ISSUE THREAD

**Issue by liyang516** [rancher/rke2#5239]
I have a k8s cluster， use v1.22.6+rke2r1 ，now I wanted upgrade k8s cluster to v1.28.3+rke2r2， what are the suggestions for upgrading step？

This cluster have 3 masters，21 workers，can I upgrade 3 masters at the save time？Or I should upgrade one node at a time?

**Comment by liyang516** [comment]
rke2 support skipping minor versions upgrading？I mean from v1.22.6 to v1.28.3

**Comment by brandond** [comment]
No. RKE2 is Kubernetes, and the Kubernetes version skew policy applies. See: https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order

You should upgrade the cluster through each intermediate minor, making sure that all cluster components on all nodes have been upgraded before proceeding on to the next version.
1. v1.22.6 -> latest v1.22 patch release
2. -> latest v1.23 patch release
3. -> latest v1.24 patch release
4. -> latest v1.25 patch release
5. -> latest v1.26 patch release
6. -> latest v1.27 patch release
7. -> latest v1.28 patch release

You have a lot of work ahead of you; this is generally why we advise keeping up with Kubernetes releases instead of waiting years to get around to upgrading. At this point it may be easier to build a new v1.28 cluster and migrate your workload over.

**Comment by liyang516** [comment]
> No. RKE2 is Kubernetes, and the Kubernetes version skew policy applies. See: https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order
> 
> You should upgrade the cluster through each intermediate minor, making sure that all cluster components on all nodes have been upgraded before proceeding on to the next version.
> 
> 1. v1.22.6 -> latest v1.22 patch release
> 2. -> latest v1.23 patch release
> 3. -> latest v1.24 patch release
> 4. -> latest v1.25 patch release
> 5. -> latest v1.26 patch release
> 6. -> latest v1.27 patch release
> 7. -> latest v1.28 patch release
> 
> You have a lot of work ahead of you; this is generally why we advise keeping up with Kubernetes releases instead of waiting years to get around to upgrading. At this point it may be easier to build a new v1.28 cluster and migrate your workload over.

tks

**Comment by hoangphuocbk** [comment]
> No. RKE2 is Kubernetes, and the Kubernetes version skew policy applies. See: https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order
> 
> You should upgrade the cluster through each intermediate minor, making sure that all cluster components on all nodes have been upgraded before proceeding on to the next version.
> 
>     1. v1.22.6 -> latest v1.22 patch release
> 
>     2. -> latest v1.23 patch release
> 
>     3. -> latest v1.24 patch release
> 
>     4. -> latest v1.25 patch release
> 
>     5. -> latest v1.26 patch release
> 
>     6. -> latest v1.27 patch release
> 
>     7. -> latest v1.28 patch release
> 
> 
> You have a lot of work ahead of you; this is generally why we advise keeping up with Kubernetes releases instead of waiting years to get around to upgrading. At this point it may be easier to build a new v1.28 cluster and migrate your workload over.

Hi @brandond, 
I read Kubernetes version skew policy, agent components such as kube-proxy and kubelet may be up to three minor versions older than kube-apiserver. IMO, I can speed up these above steps, by upgrading server components on server nodes from v1.22.6 -> latest v1.22 patch -> latest v1.23 patch -> latest v1.24 patch -> latest v1.25 patch then upgrade all agent nodes from v1.22.6 to latest v1.25 patch.
 With that I can upgrade our cluster quickly because agent nodes can be up to hundreds while server nodes are just 3 or 5.
I would appreciate it if you could kindly advise. Thanks!

**Comment by brandond** [comment]
Yes, if you wanted to leave the agents down-revision for a bit, you could probably technically get away with that. We don't test that; we generally upgrade all cluster members before proceeding to the next minor, but you're welcome to give it a try.
