### ISSUE TITLE
Update canal version to include flannel v0.24.4 to fix issue with unable to run iptables-restore

### ISSUE THREAD

**Issue by curantes** [rancher/rke2#5650]
We upgraded to v1.28.8 and use canal cni and got hit by bug https://github.com/flannel-io/flannel/issues/1906.

My first question if this bug just causes a lot more logging or if there is potential problems with it or performance hit.

Second is if you plan to release a hotfix to update canal to include flannel v0.24.4 release prior to rke2 v1.28.9 is released.

I have noticed that you have already prepared the rke2-chart bump to include it in https://github.com/rancher/rke2-charts/pull/428

**Environmental Info:**
RKE2 Version: v1.28.8+rke2r1

**Comment by brandond** [comment]
cc @rbrtbnfgl @manuelbuil  I'm pretty sure you're planning on pulling through the chart update for the April release, correct?

**Comment by curantes** [comment]
Thanks for the confirmation

**Comment by Raoul555** [comment]
I'm hit also with this bug.

The message "Failed to ensure iptables rules: error setting up rules: failed to apply partial iptables-restore unable to run iptables-restore (, ): exit status 4", is it just a warning, and flannel is still fully functional ?

I'm asking, because in my v1.27.12+rke2r cluster, I've got a network issue. Pods is unable to communicate between each others. Ping fails from a pod to an other one. So, I'm wondering if this flannel bug can de the cause of my communication problem.

**Comment by endawkins** [comment]
### Validated on master using commit 95e13dc | version 1.29

```
Cluster nodes:
 ip-[redacted].us-east-2.compute.internal   Ready   control-plane,etcd,master   83s   v1.29.3+rke2r1   [redacted]   [redacted]   SUSE Linux Enterprise Server 15 SP4   5.14.21-150400.22-default   containerd://1.7.11-k3s2
```

```
kubectl get node -o yaml | grep 'hardened-flannel' -A1
      - docker.io/rancher/hardened-flannel@sha256:[redacted]
      - docker.io/rancher/hardened-flannel:v0.25.0-build20240410
      sizeBytes: 81789820
```
