### ISSUE TITLE
Doc: clarify "Certificate Rotation"

### ISSUE THREAD

**Issue by flokli** [rancher/rke2#589]
https://docs.rke2.io/advanced/#certificate-rotation says:

> By default, certificates in RKE2 expire in 12 months.

> If the certificates are expired or have fewer than 90 days remaining before they expire, the certificates are rotated when RKE2 is restarted.

Does this mean certificates are only renewed when I restart `rke2-server`? This seems quite disruptive -is there no automatic renewal process?

**Comment by bencardinal** [comment]
I would also like to know the answer to this question.  Is there a way to proactively rotate the certificate for rke2?  The [rke docs](https://rancher.com/blog/2019/kubernetes-certificate-expiry-and-rotation-in-rancher-kubernetes-clusters) outline a method to do so.  Will those steps work for rke2?

**Comment by brandond** [comment]
Both K3s and RKE2 only rotate certificates on startup. We do not currently have a documented method to rotate certificates out-of-band. Since certificates are only loaded on startup, any manual rotation would require restarting RKE2 anyway to load the new certificates, at which point you might as well just let it rotate the certificates itself. It is kind of expected that you would be taking your hosts down periodically for patching and upgrading every few months anyways.

Note that restarting rke2-server is NOT disruptive to workload pods - they remain running and functional even when the server or agent itself is not running.

**Comment by Martin-Weiss** [comment]
As a first step do we have a process to add certificate monitoring and alerting to prometheus and a dashboard to grafana?
With regular updates the reboots should happen - but reality has shown that customers do not patch / reboot for more than 3 months.. so there is a risk that the certificates expire within the 90 days..

**Comment by brandond** [comment]
Monitoring of that sort would live in Rancher, so I'm not sure.

**Comment by Martin-Weiss** [comment]
> 
> 
> Monitoring of that sort would live in Rancher, so I'm not sure.

Just created an issue on Rancher for this.. https://github.com/rancher/rancher/issues/31757

**Comment by bovy89** [comment]
We still need more info about that

**Comment by brandond** [comment]
More info about what?

**Comment by bovy89** [comment]
How to rotate certificate if needed

**Comment by hectoralicea** [comment]
For RKE2, does this mean, that to rotate the certs we just need to reboot each of the master and nodes?

**Comment by hectoralicea** [comment]
> For RKE2, does this mean, that to rotate the certs we just need to reboot each of the master and nodes?

yep, that seemed to solve my problem, where my Jenkins running on RKE2 complained about expired SSH keys, even thought SSH keys cant expire.  Appears it had nothing to do with expired SSH keys, but rather the RKE2 certs expired.  Appears some of my servers have not been rebooted in over a year, so jenkins was spitting out the following error
```
CertificateExpiredException: NotAfter: Wed Jul 13 14:54:24 EDT 2022
```
