### ISSUE TITLE
Support Install Feature of using commit id

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#62]
Installation using commit id fails at download
```
INSTALL_RKE2_COMMIT=1dd8d99d86daac97b2cf2a060288c86e0059e7b6 ./install.sh 
[INFO]  using commit 1dd8d99d86daac97b2cf2a060288c86e0059e7b6 as release
[INFO]  downloading hash https://storage.googleapis.com/rke2-ci-builds/rke2-1dd8d99d86daac97b2cf2a060288c86e0059e7b6.sha256sum
root@ip-172-31-4-195:~# 
```

**Comment by briandowns** [comment]
Infrastructure and configuration is needed to facilitate this like k3s. This has been deprioritized in favor of actual bugs. Git checkout at the desired commit and building is best strategy for now.

**Comment by davidnuzik** [comment]
Workaround for using commit id is to leverage git and make for now.

**Comment by davidnuzik** [comment]
As I understand the current state of things -- we may not need this in the install script as it may be going away. Based on Hussein's changes around versioning and the CI / Make'ing he is the best candidate to take on this functionality.

QA has a need to easily test from commit id so that they do not need to wait for a new beta or rc release. We have tried testing by cloning and make from commit but this is a burden and causes a lot of overhead for testing. I believe I can speak for QA when I say they will be eternally grateful if we have some simpler solution for running rke2 from a specific commit id.

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 version v1.20.5-rc2+rke2r1 (2355feae77669ef3b60e8570c8a0fa22b7080185), installing through commit id is successful.
On Ubuntu 20.04
On Centos8.2 installation using commit ID is successful as well. It currently uses tarball method which means SELinux cannot be tested using commit ID at this point. 

```
curl -sfL https://get.rke2.io| sudo INSTALL_RKE2_COMMIT=2355feae77669ef3b60e8570c8a0fa22b7080185 sh -
[INFO]  using commit 2355feae77669ef3b60e8570c8a0fa22b7080185 as release
[INFO]  downloading airgap checksums at https://storage.googleapis.com/rke2-ci-builds/rke2-images.linux-amd64-2355feae77669ef3b60e8570c8a0fa22b7080185.tar.zst.sha256sum
[INFO]  downloading airgap tarball at https://storage.googleapis.com/rke2-ci-builds/rke2-images.linux-amd64-2355feae77669ef3b60e8570c8a0fa22b7080185.tar.zst
[INFO]  downloading checksums at https://storage.googleapis.com/rke2-ci-builds/rke2.linux-amd64-2355feae77669ef3b60e8570c8a0fa22b7080185.tar.gz.sha256sum
[INFO]  downloading tarball at https://storage.googleapis.com/rke2-ci-builds/rke2.linux-amd64-2355feae77669ef3b60e8570c8a0fa22b7080185.tar.gz
[INFO]  verifying airgap tarball
[INFO]  installing airgap tarball to /var/lib/rancher/rke2/agent/images
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local
```
