### ISSUE TITLE
updatecli: add typefilter `latest: true`

### ISSUE THREAD

**Issue by mgfritch** [rancher/rke2#6371]
We need to ensure UpdateCli is choosing the tagged `latest` release,
instead of creating PRs that actually bump the version backward by
selecting the most recent chronological release

See also: https://github.com/rancher/image-build-node-feature-discovery/pull/35

**Comment by mgfritch** [comment]
Hey, thanks @olblak ! 👋 

Generally, we select a release based on what's tagged as the latest (stable) upstream and then package/validate this release via our downstream chart(s).

Your first `semver` example appears to accomplishes exactly what we want, but we'd also like to see UpdateCli open a separate PR for each of these version bumps, instead of amending to the [existing PR](https://github.com/rancher/image-build-node-feature-discovery/pull/35).

I'm a little unclear on the documentation, but perhaps this can be accomplished by setting `workingbranch: true` on the [git scm](https://www.updatecli.io/docs/plugins/scm/git/) ?

**Comment by olblak** [comment]
> Generally, we select a release based on what's tagged as the latest (stable) upstream and then package/validate this release via our downstream chart(s).

It makes sense

> I'm a little unclear on the documentation, but maybe this can be accomplished by setting workingbranch: true on the [git scm](https://www.updatecli.io/docs/plugins/scm/git/) ?

`workingbranch=false` allows you to commit directly to the targeted branch like `main` without using a working branch.
for historical reason and to not introduce breaking changes, the git scm has `workingbranch` set to `false` by default while all other scm (github,gitea,etc) set to `true`

I usually advance to not commit to a directly to the main branch without some sort of validation because then you put a lot of trust on that upstream dependency maintainer

> we'd also like to see UpdateCli open a separate PR for each of these version bumps, instead of amending to an https://github.com/rancher/image-build-node-feature-discovery/pull/35

I don't see a way to achieve that in the current situation.
I must admit it's a scenario I never considered, why would you prefer a different pull request?

**Comment by mgfritch** [comment]
> > we'd also like to see UpdateCli open a separate PR for each of these version bumps, instead of amending to an [rancher/image-build-node-feature-discovery#35](https://github.com/rancher/image-build-node-feature-discovery/pull/35)
> 
> I don't see a way to achieve that in the current situation. I must admit it's a scenario I never considered, why would you prefer a different pull request?

Using the [attached PR](https://github.com/rancher/image-build-node-feature-discovery/pull/35) as an example, we could have merged the one desired pull request while closing out any additional undesired pull requests ... 

However, maybe that would be a moot issue if we had used the `semver` versionfilter, because the pull request would have been updated iff there was a matching semver release greater than the release posted in the open PR?
