### ISSUE TITLE
rpm with system-upgrade-controller does only replace binary and not upgrade yum?

### ISSUE THREAD

**Issue by jonaz** [rancher/rke2#661]
When using https://docs.rke2.io/upgrade/automated_upgrade/

It looks like in rpm installations of rke2 the rpm package is not upgraded but only the `/usr/bin/rke2` is replace with new version. 
Is this intentional? `yum info rke2-server` will show one version and the `/usr/bin/rke2` is a totally other version? 

Would a better approach to use yum in the upgrade plan container?

**Comment by cjellick** [comment]
We debated this a lot. It is a good question.
Truth be told, we do not like the idea of running yum commands from inside the SUC job.

We want to stay with the upgrading the binary, but we need an approach that does not stomp on files installed by the RPM. We have this idea for a "staging" directory where we (SUC) can drop a binary and the next restart of rke2 would pick it up. The files in this directory would not be under RPM management.

One of our main hesitations is that we don't want to have to rely on the RPM repository being there and populated. So, another option could be that the upgrade container bakes-in the actual RPM and installs via a local rpm -i call, rather than a yum command.

**Comment by jonaz** [comment]
rpm -i baked in seems like the 'best' solution. Perhaps we should just stop using RPM's. But we need the selinux stuff in there. Running centos 8.

**Comment by cjellick** [comment]
Yep. That's exactly what we're thinking: we dont _really_ need to install rke2 via rpm, but for selinux.
