### ISSUE TITLE
Agent nodes remain in not ready when started in parallel with servers

### ISSUE THREAD

**Issue by mynktl** [rancher/rke2#6931]
**Environmental Info:**
RKE2 Version: 1.30

Node(s) CPU architecture, OS, and Version:  RHEL 9

Cluster Configuration: 3 nodes, 3 agent

**Describe the bug:**

If all nodes, including servers and agents are started at once, few of agent node remain in NotReady state.
Refer this screenshot for more details:
![image](https://github.com/user-attachments/assets/109846cc-e2dc-452f-a316-70b089727fe9)

Here, terminal window having title asrobot0 and agent0 is in notReady state and if you check the logs, It is still waiting for apiServer endpoint.

**Workaround**:
Post restarting these notReady state, It becomes ready.

**Steps To Reproduce:**
Configure multi-node setup with 3 agent nodes and start all server + agent at the same time.

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

All nodes should be in ready state.

**Additional context / logs:**

**Comment by brandond** [comment]
v1.30.1+rke2r1 is several months old. Please try again with the most recent release (v1.30.5-rke2r1 if you want to stick with 1.30) and let us know if you continue to see this issue.

**Comment by vineetsingh5** [comment]
> v1.30.1+rke2r1 is several months old. Please try again with the most recent release (v1.30.5-rke2r1 if you want to stick with 1.30) and let us know if you continue to see this issue.

Do we know what updates are available in v1.30.5-rke2r1 that could resolve this issue?

**Comment by brandond** [comment]
There have been several improvements to the agent loadbalancer since the May release cycle. You can check out the K3s and RKE2 changelogs for a complete list; I do not have a single specific change to point you at. It is a best practice to confirm that your problem is still present on the latest release before opening an issue, in order to avoid spending time diagnosing an issue that has already been resolved.
