### ISSUE TITLE
Can't start kine backend database as static pod to replace etcd

### ISSUE THREAD

**Issue by jomeier** [rancher/rke2#7332]
Hi,

I try to start a mariadb static pod as a kine backend to replace etcd. 

If I start mariadb with systemd and create a etcd database. Everything works as expected.

If I start a static pod by creating a mariadb pod yaml in 
/var/lib/rancher/rke2/agent/pod-manifests

and start the rke2-server systemd service, I get an immediate error in the journal logs, that nothing is listening on port 3306.

I would expect, that RKE2 starts all static pods (also MariaDB) and AFTERWARDS tries to connect to ETCD -> kine (and therefore also to MariaDB) plus: ETCD on its own is also started as a static pod.

Is that currently not possible?

Thanks and greetings,
Josef

**Comment by brandond** [comment]
Don't do that. As I said when you asked on Slack:

> If you're going to use an external SQL DB, it's recommended that you use something that's externally managed and has more reliability than your rke2 nodes. If you're just running a local datastore you're better off just using etcd. Adding kine but using a local DB is additional complication with no benefit.

**Comment by brandond** [comment]
We are not planning on supporting external datastore running IN the cluster as static pods, regardless of the datastore type. We are able to do that with etcd because we manage its configuration and are able to ensure that it comes up in the correct sequence - but this is not easy to accomplish with arbitrary 3rd party databases.

I will also note that NATS does not currently pass kubernetes conformance tests. Ref: https://github.com/k3s-io/kine/pull/321
