### ISSUE TITLE
Using a self-signed cert for Helm Chart repo

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#736]
_Originally posted by @Martin-Weiss in https://github.com/rancher/rke2/issues/224#issuecomment-787024112_

Quick question on this topic.. we have helm charts on a central server using a self-signed certificate. Now it seems that the job does not fetch the tgz due to missing trust to certificates from that self-signed CA. Do I miss the point where I can specify which CA to trust for helm chart pull?

**Comment by brandond** [comment]
The easiest way to do that would probably be to build your own klipper-helm image that builds on top of the stock rancher/klipper-helm image and adds your cert to the trust store. You can use your image by specifying your image in the jobImage field of the HelmChart manifest.

**Comment by Martin-Weiss** [comment]
Thanks for the fast reply! Yes -  that might be a good / quick workaround..
Unfortunately building own images breaks the trusted and secure delivery chain and might also cause problems during future updates / upgrades / support.. do you thing it makes sense to create a feature request to trust the „hosts“ trusted CAs automatically?

**Comment by brandond** [comment]
Curious what you're using for trust / secure delivery? Our images aren't signed for Notary or anything. Image digests are mostly just for integrity checking (and they are easy to use as unique blob IDs) and aren't really suitable for establishing provenance. If you're just building on top of an existing image using FROM in a Dockerfile, the base layers are still there and just as verifiable as they were before you laid down additional content on top of them.

Regardless - it's worth opening an issue over on the k3s-io/helm-controller repo to add a Chart Repo CA field to the HelmChart CRD, but honestly this sort of customization is exactly why the it currently has the jobImage field.

**Comment by Martin-Weiss** [comment]
> 
> 
> Curious what you're using for trust / secure delivery? Our images aren't signed for Notary or anything. Image digests are mostly just for integrity checking (and they are easy to use as unique blob IDs) and aren't really suitable for establishing provenance. 

Currently this is handled by "processes" and not with "technical implementations". So there is a trusted chain where we control at a single "gateway registry" what is coming in and what can be used on which k8s cluster. And the process does not allow modification on images from external sources. On a "long term" this will be enhanced by signing etc.

> If you're just building on top of an existing image using FROM in a Dockerfile, the base layers are still there and just as verifiable as they were before you laid down additional content on top of them.
> 

The challenge is that we have this problem basically with "all images and containers" running within k8s - so maybe we should think about adding sidecars or init containers that "inject" the trusted CAs from the host OS or from a given source into the containers..

> Regardless - it's worth opening an issue over on the k3s-io/helm-controller repo to add a Chart Repo CA field to the HelmChart CRD, but honestly this sort of customization is exactly why the it currently has the jobImage field.

Thanks - will do...

**Comment by Martin-Weiss** [comment]
Adding to the discussion here - we still need to find a way to add "trusted CAs" to the helm job container so that helm charts can be downloaded from a central customer provided helm chart store that is provided via https access and using a certificate from a self signed CA.

IMO we should find a way to "trust" the CA that is added to the hosts "/etc/ssl/ca-bundle.pem".. we have to add trusted CAs on the hosts for fetching other content - i.e. also the CA cert from the CA used for the registry (configs:...tls:..ca_file: /etc/ssl/ca-bundle.pem in /etc/rancher/rke2/registries.yaml)

So beside adding trust for the CA used in k8s - can we add a trust to the CAs in /etc/ssl/ca-bundle.pem or any other further CAs?
As this is required already during bootstrap - I believe a CRD "containing" the certificates might not be sufficient because of the order dependencies and because this might also cause a race-condition during bootstrap.

So what about allowing to "map" "/etc/ssl/ca-bundle.pem" into the helm install container?
Or what about adding the global trust to "/etc/ssl/ca-bundle.pem" also as config option in rke2 config.yaml?

P.S. for the "big picture" -  trusting the self-signed CAs is also a general problem in many other applications we deploy in K8S - so for the majority of deployments we have a separate "trusted CAs" option - but on the operator and customer side of things we really need a central and one-to-many point to manage these.. not sure if on a long term this requires an other operator or if this should be part of cert-manager or rke2..... but as operator of the cluster I also need a global overview of "who trusts what, where are which certificates used, when do they expire etc..".. for the time being "/etc/ssl/ca-bundle.pem" would be such a "central place"

**Comment by brandond** [comment]
@Martin-Weiss this sounds like a much larger problem than just needing to pass a cert into the helm job. If this is critical to a customer use case, please make sure you bring it up to product management so that we can prioritize a fix.

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss this sounds like a much larger problem than just needing to pass a cert into the helm job. If this is critical to a customer use case, please make sure you bring it up to product management so that we can prioritize a fix.

I believe we might need

1. a short term fix to have an official supported way to get helm charts downloaded from an on-premise helm chart web-server that is using self-signed SSL certificates for HTTPs and 
2.  a solution for "long term" / "big picture" to manage the trust to CAs of clusters and applications / services i.e. via rancher or sidecars or via global trust to the hosts trusted CAs.. maybe managed via Rancher..

**Comment by Martin-Weiss** [comment]
This still needs to be looked at
