### ISSUE TITLE
Provide multus + sriov-cni support

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#746]
The task requires:

- [X] Images for multus, sriov-operator, sriov-cni, sriov-network-device-plugin, sriov-network-config-daemon, sriov-injector and infiniband-sriov
1. https://hub.docker.com/r/rancher/hardened-sriov-network-operator
2. https://hub.docker.com/r/rancher/hardened-sriov-cni
3. https://hub.docker.com/r/rancher/hardened-sriov-network-device-plugin
4. https://hub.docker.com/r/rancher/hardened-multus-cni
5. https://hub.docker.com/r/rancher/hardened-sriov-network-resources-injector
6. https://hub.docker.com/r/rancher/hardened-ib-sriov-cni

- [x] Update images to the new UBI version

- [x] rke2-chart for multus
prototype ==> https://github.com/jcaamano/rke2-charts/tree/sriov/packages/rke2-multus/charts

- [x] rke2-chart for sriov-operator
prototype ==> https://github.com/jcaamano/rke2-charts/tree/sriov/packages/rke2-sriov

- [x] documentation
- [ ] QA tests

**Comment by manuelbuil** [comment]
For rke2-chart tasks to complete, we need to wait for Thursday's design meeting. Non-essential parts (but recommended) of the sriov controller require a 3rd party to provide certificates in order for the kube-api to interact with it (a Mutatingcontroller and a Validatingcontroller). Initial tests of the essential parts work with those prototypes

**Comment by jcaamano** [comment]
The sriov charts right now are using the old build scripts and need to be migrated to the new ones.

Another problem we are dealing with is certificate management for the webhooks it deploys. Until this is resolved the webhooks are disabled as they are not strictly necessary for operation.

The operator deploys three webhooks:
* A validating webhook for it's own CRD SriovNetworkNodePolicy, self explanatory.
* A mutating webhook for it's own CRD SriovNetworkNodePolicy, fill's it with omitted default values.
* A mutating webhook that's adds the resource name associated to a network attachment definition to the pod spec as a resource request. This avoids having the user specify it two times in two different places.

The api server needs to authenticate these webhooks and certificates need to be provided for this. For openshift, these webhooks are deployed with annotations that make an openshift specific operator to generate and rotate these certificates. There is no equivalent solution provided for other kubernetes platforms.

Current options are:
* Generate and rotate this certificates manually via script or helm chart.
* Depend on cert-manager and add it's specific annotations to the webhooks.
* Cook in the operator some kind of certificate self-management. These certificates might be self-signed or signed by the cluster CA if the operator has the proper roles.

IMO, the preferred option would be the last one. It seems reasonable since the operator itself is responsible for the webhook configuration as well as the services that serve those webhooks. For the first option, adding yet another manual procedure for certificate rotation than the one is already in place for RKE2 cluster CAs does not seem the best thing to do (but perhaps rke2 binary could be made aware of other certificates to generate or rotate?). For the second option, adding a dependency of what could be considered a system chart, sriov-operator, to a another component, that might or might not be available in the cluster or not considered a system component also might not be the best thing to do.

**Comment by manuelbuil** [comment]
When building the images in the hardened-rancher-way, the image is built using rancher/hardened-build-base image which is based on Alpine. Then, the binary is moved and executed in a UBI-based image. In Alpine, there is no libc but a lightweight alternative called musl, which is not in UBI.

There is a component in the sriov controller that, unfortunately, runs a dynamically-linked binary that depends on libc. As we are building in an Alpine-based image, it depends on musl, which is not in UBI and thus the binary fails to run.

The current community approach (using buildmode=plugin) does not allow to make the binary statically linked. Therefore, for the time being, I suggest building the binary in a "not-hardened" way, i.e. based on golang:1.13 instead of rancher/hardened-build-base. That golang:1.13 image uses libc and thus the built binary should be compatible with UBI. I feel this should be ok because as far as I understood, the hardened-images is a requirement for rancher-federal and multus-sriov is not a requirement in that space

**Comment by manuelbuil** [comment]
All Multus+sriov images are now based on hardened builds

> When building the images in the hardened-rancher-way, the image is built using rancher/hardened-build-base image which is based on Alpine. Then, the binary is moved and executed in a UBI-based image. In Alpine, there is no libc but a lightweight alternative called musl, which is not in UBI.
> 
> There is a component in the sriov controller that, unfortunately, runs a dynamically-linked binary that depends on libc. As we are building in an Alpine-based image, it depends on musl, which is not in UBI and thus the binary fails to run.
> 
> The current community approach (using buildmode=plugin) does not allow to make the binary statically linked. Therefore, for the time being, I suggest building the binary in a "not-hardened" way, i.e. based on golang:1.13 instead of rancher/hardened-build-base. That golang:1.13 image uses libc and thus the built binary should be compatible with UBI. I feel this should be ok because as far as I understood, the hardened-images is a requirement for rancher-federal and multus-sriov is not a requirement in that space

All Multus+sriov images are now based on hardened builds

**Comment by manuelbuil** [comment]
There is an issue with the current webhooks in the sriov operator:
```

**Comment by davidnuzik** [comment]
@manuelbuil at your next availability could you post as a comment here a brief update with the status on this effort? Thanks!

**Comment by manuelbuil** [comment]
both sriov and multus charts are merged into rke2-charts. Therefore, the functionality is now available. Docs PR under review: https://github.com/rancher/rke2/pull/927

**Comment by brandond** [comment]
Do you have a PR in to add them to the CNI list?

**Comment by manuelbuil** [comment]
> Do you have a PR in to add them to the CNI list?

We can discuss about this but I wouldn't add multus to the CNI list. Multus is a CNI multiplexer that requires a main CNI, i.e. multus by itself does nothing. The current approach is that whatever gets chosen in the `--cni` will become that main CNI option for Multus when the Multus HelmChart gets deployed

**Comment by brandond** [comment]
Interesting. How are we planning on plumbing in Multus then? Will it get another dedicated CLI flag? Or I suppose we could add some special handling for something like `--cni=multius+canal` for example

**Comment by manuelbuil** [comment]
Just missing the SRIOV helm chart. In review ==> https://github.com/rancher/charts/pull/1211#pullrequestreview-668492770

**Comment by davidnuzik** [comment]
Assigned to @rancher-max to take point on Multus testing and Multus plus SR-IOV testing on bare metal.

**Comment by cjellick** [comment]
Slightly lower priority to test before the release since the sr-iov chart release is an out-of-band release

**Comment by manuelbuil** [comment]
Added docs on how to test multus+macvlan and multus+sriov: https://confluence.suse.com/display/RKE2/CNI+Test+Plan

**Comment by rancher-max** [comment]
Found an issue with Selinux enforcing nodes while testing on v1.21.2-rc1+rke2r1. The initcontainer is not privileged which causes write to fail:
```
$ k logs -n kube-system pod/kube-multus-ds-2v4dz -c cni-plugins
/host/opt/cni/bin is non-writeable, skipping
```
And then subsequently prevents pods from using its network:
```
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               48s   default-scheduler  Successfully assigned default/pod-macvlan to ip-172-31-15-57.us-east-2.compute.internal
  Normal   AddedInterface          47s   multus             Add eth0 [10.42.3.104/32]
  Warning  FailedCreatePodSandBox  47s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1e377e177179c8e0004790bf6866744b2f6c7a825fd3558aa15f5a67f62a9896": [default/pod-macvlan:macvlan-conf]: error adding container to network "macvlan-conf": failed to find plugin "macvlan" in path [/opt/cni/bin /opt/cni/bin]
```

Updating the multus daemonset to have `securityContext.privileged: true` fixes this.

**Comment by rancher-max** [comment]
Validated selinux fix using commitid: `790186ffa54ab4c87a09d1835316e3aa55f59fb4` on release-1.21 branch.
Multus with canal, cilium, and calico has been validated on Ubuntu and Centos8 with Selinux enforcing. Leaving this open to validate sriov.

**Comment by brandond** [comment]
Do we still need to validate SRIOV since it's being handled as a standalone chart in rancher-charts?

**Comment by rancher-max** [comment]
#### Validated using v1.21.2+rke2r1 per our SRI-OV CNI Test Plan

- SRI-OV specific checks pass
- Standard networking checks continue to pass
