### ISSUE TITLE
Define install.sh environment variables INSTALL_RKE2_RPM_SITE and INSTALL_RKE2_RPM_TESTING_SITE

### ISSUE THREAD

**Issue by ron1** [rancher/rke2#811]
Some airgap environments mirror yum content such as https://rpm.rancher.io/rke2/stable/common/centos/7/noarch to their internal networks. In order for RKE2 to better support these environments, define `install.sh` environment variables `INSTALL_RKE2_RPM_SITE` and `INSTALL_RKE2_RPM_TESTING_SITE` in place of hardcoded `rpm_site` variables set [here](https://github.com/rancher/rke2/blob/d0685892f69477a50b7466a2a8d73e83983d62a8/install.sh#L392,L394).

**Comment by brandond** [comment]
Note that you can't just mirror the RPMs, you'd need to mirror the complete Yum repo. In an airgap environment it might be easier to just manually perform the install in a way that works best for you, since the only value it really provides on RPM-based systems is creating a repo config file and running a yum command.

**Comment by ron1** [comment]
Yes, in this environment the entire rancher yum repo is being mirrored as are numerous other yum repos.
