### ISSUE TITLE
Test and Certify SLES 15 SP3

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#816]
Test and Certify SLES 15 SP3

**Comment by davidnuzik** [comment]
Lower priority compared to all other issues to test in this milestone. These can be tested day after release even (if needed).

**Comment by davidnuzik** [comment]
Moved to 1.20.7 milestone. Won't be released until June, however we should test it soon so it can land on the next 2.5.x support matrix.

**Comment by davidnuzik** [comment]
Not released yet, moving to a future milestone (next for June)

**Comment by rancher-max** [comment]
#### Validated using v1.21.1-rc3+rke2r1, v1.20.7+rke2r2, and v1.19.11+rke2r1

Validated per our New OS Matrix:


Test Case | Status | Comments
-- | -- | --
Fresh Installation and sonobuoy execution | Pass | On 1.21, we should disable ingress before running this. This is known, otherwise "Ingress API should support creating Ingress API operations" fails.
Run functional tests on imported RKE2 cluster on Rancher | Pass | &nbsp;
Upgrade SUC RKE2 native with workloads | Pass | &nbsp;
Install RKE2 as local management cluster for Rancher | Pass | &nbsp;
