### ISSUE TITLE
[docs] In HA installs, wait for the first node to be ready before joining others

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#895]
Need to update documentation to call out the importance of waiting for the initial node to be running before joining other server nodes, due to the limitations in etcd learners.

**Comment by Martin-Weiss** [comment]
When updating the docs with this - please also add the info on how to test local and remote if the first node is ready and etcd is not in a status where an other secondary master is in process of joining..

**Comment by massep88** [comment]
Maybe something interesting to add in the doc : While experiencing issues with a simultaneous rke2 / etcd servers start, I could validate that for example a 1s wait between rke2 / etcd starts was ok.

**Comment by teebeey** [comment]
Is this only when joining the second master, or do we have to wait between all the masters joining?

**Comment by massep88** [comment]
Yes and this would be great if this is included in the documentation.
Validating above @brandond comment I have re-tested this, adding a specific test for etcd launch on the previous master before moving on with the next one.

**Comment by davidnuzik** [comment]
@brandond why did you unassign @rancher-max ?
cc: @cjellick

**Comment by brandond** [comment]
When running through this in the meeting after @cjellick dropped and asked the rest of us to finish moving things out of the v1.21.2+rke2r1 milestone, when this came up @rancher-max indicated that it was unclear why he was assigned an issue that's still in Next Up. If he's expected to write the documentation and put in the PR then someone needs to make that clear to him.

**Comment by davidnuzik** [comment]
Oh okay gotcha. @rancher-max and I synced on this and he agreed he could do the docs work here previously. I'll reassign to him.

**Comment by braunsonm** [comment]
Can this limitation be wrapped by `rke2 server` rather than relying on the user to stagger the joining of master nodes? RKE2's binary could do an random exponential backoff and retry rather than require the delay. 

This means bootstrapping RKE2 clusters using tools like Terraform get a little more painful. Typically you'd create a group of master nodes using something like a `for_each` or `count` meta-argument like so:

```hcl
resource "virtual_machine" "server_nodes" {
  for_each = {
    master1 = 1.1.1.1
    master2 = 1.1.1.2
    master3 = 1.1.1.3
  }

 ....
}
```

The only way to truly force the first server node to be online before creating the others is to introduce dependencies between server nodes. This creates a lot of problem because if you need to recreate the 1st server node, all the dependencies need to be destroyed which destroys the whole server plane.

The other option which is more of a hack, is when your `cloud-init` script runs `systemctl enable --now rke2-server` to introduce a sleep infront which _hopefully_ is enough of a wait to ensure the previous node has joined. This doesn't work a lot of the time.

**Comment by brandond** [comment]
You do need to have dependencies between nodes though - exactly one of your nodes must be started with --cluster-init, the remainder must be started with --server pointing at that first server, or at some other fixed registration endpoint that is backed by that server.

**Comment by braunsonm** [comment]
@brandond If you need to wait for the `--cluster-init` node to be **completed** before starting the others, then you do have a dependency of sorts when you initially create the cluster.
Thanks I've subscribed to that ticket.

**Comment by rancher-max** [comment]
This doesn't really apply anymore as in all of the latest releases it is actually possible to run all the rke2-server processes at the same time, so I'm going to close this docs issue. See https://github.com/rancher/rke2/issues/349 for details on the fix.
