### ISSUE TITLE
Network Problems

### ISSUE THREAD

**Issue by jeluizferreira** [rancher/rke2#974]
Hi,
When I install RKE2 via talbar in ubuntu 20.04.2, with or without custom Cluster and Services CIDR, there are some network problems. Aparently, the containers cannot access the outside world. This is exposed in coreDNS, that cannot translate addresses, becouse it do not access the host's dns servers.
I made it work with 192.168.X.X Cluster and Services customizations. Any other addresses that I used had problems. I tryed 172.16.X.X and 10.16.X.X.
My company network (that is very large) utilizes a 10.0.0.0/8, and I can utilize only some 10.16.X.X addresses (two /22).
The default gateways of my organization routes 10.0.0.0 to other company routers, as does with some 172.16 and 172.40 too.
Thx for any help.

**Comment by Sicaine** [comment]
I'm just an rke2 beginner but perhaps this can help you:

It could be that you need to configure the masquerade configuration of your cni.

You need to make sure that your node ips have an ip range in your two /22 networks and your container ips are masqueraded so that your container ips with your private range are using the node ip when leaving your node.

I would also limit the exposure of your nodes to your company network and would add a loadbalancer up-front. Only your loadbalancer would need an ip from your company network.


You also mentioned dns resolution issues; You might need to configure a stub domain for your internal domains or point to your companies dns server completly:
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns

I'm not sure if this is the issue or if you have two different issues: networking and dns
